SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
START TRANSACTION;

INSERT INTO `countries` (`code`, `name`, `region`, `subregion`) VALUES
('GLOBAL', 'Global Registry', 'Global', ''),
('AD', 'Principality of Andorra', 'Other', ''),
('AE', 'United Arab Emirates', 'Asia', 'Western Asia'),
('AF', 'Islamic Republic of Afghanistan', 'Other', ''),
('AG', 'Antigua and Barbuda', 'Americas', 'Caribbean'),
('AI', 'Anguilla', 'Americas', 'Caribbean'),
('AL', 'Republic of Albania', 'Other', ''),
('AM', 'Republic of Armenia', 'Asia', 'Western Asia'),
('AN', 'Netherlands Antilles', 'Americas', 'Caribbean'),
('AO', 'Republic of Angola', 'Other', ''),
('AQ', 'Antarctica', 'Other', ''),
('AR', 'Argentine Republic', 'Americas', 'South America'),
('AS', 'American Samoa', 'Oceania', 'Polynesia'),
('AT', 'Republic of Austria', 'Other', ''),
('AU', 'Australia', 'Oceania', 'Australia and New Zealand'),
('AW', 'Aruba', 'Americas', 'Caribbean'),
('AX', 'Åland Islands', 'Other', ''),
('AZ', 'Republic of Azerbaijan', 'Asia', 'Western Asia'),
('BA', 'Republic of Bosnia and Herzegovina', 'Other', ''),
('BB', 'Barbados', 'Americas', 'Caribbean'),
('BD', 'People''s Republic of Bangladesh', 'Asia', 'Southern Asia'),
('BE', 'Kingdom of Belgium', 'Europe', 'Western Europe'),
('BF', 'Burkina Faso', 'Africa', 'Western Africa'),
('BG', 'Republic of Bulgaria', 'Europe', 'Eastern Europe'),
('BH', 'Kingdom of Bahrain', 'Asia', 'Western Asia'),
('BI', 'Republic of Burundi', 'Africa', 'Eastern Africa'),
('BJ', 'Republic of Benin', 'Africa', 'Western Africa'),
('BL', 'Saint Barthélemy', 'Other', ''),
('BM', 'Bermuda', 'Americas', 'Northern America'),
('BN', 'Brunei', 'Asia', 'South-Eastern Asia'),
('BO', 'Bolivia', 'Americas', 'South America'),
('BQ', 'Caribbean Netherlands', 'Other', ''),
('BR', 'Federative Republic of Brazil', 'Americas', 'South America'),
('BS', 'Commonwealth of the Bahamas', 'Americas', 'Caribbean'),
('BT', 'Kingdom of Bhutan', 'Asia', 'Southern Asia'),
('BV', 'Bouvet Island', 'Other', ''),
('BW', 'Republic of Botswana', 'Africa', 'Southern Africa'),
('BY', 'Republic of Belarus', 'Europe', 'Eastern Europe'),
('BZ', 'Belize', 'Americas', 'Central America'),
('CA', 'Canada', 'Americas', 'Northern America'),
('CC', 'Cocos (Keeling) Islands', 'Oceania', 'Australia and New Zealand'),
('CD', 'Democratic Republic of the Congo', 'Africa', 'Middle Africa'),
('CF', 'Central African Republic', 'Africa', 'Middle Africa'),
('CG', 'Republic of the Congo', 'Africa', 'Middle Africa'),
('CH', 'Swiss Confederation', 'Europe', 'Western Europe'),
('CI', 'Côte d’Ivoire', 'Other', ''),
('CK', 'Cook Islands', 'Oceania', 'Polynesia'),
('CL', 'Republic of Chile', 'Americas', 'South America'),
('CM', 'Republic of Cameroon', 'Africa', 'Middle Africa'),
('CN', 'People''s Republic of China', 'Asia', 'Eastern Asia'),
('CO', 'Republic of Colombia', 'Americas', 'South America'),
('CR', 'Republic of Costa Rica', 'Americas', 'Central America'),
('CU', 'Republic of Cuba', 'Americas', 'Caribbean'),
('CV', 'Republic of Cabo Verde', 'Africa', 'Western Africa'),
('CW', 'Curaçao', 'Other', ''),
('CX', 'Christmas Island', 'Oceania', 'Australia and New Zealand'),
('CY', 'Republic of Cyprus', 'Europe', 'Southern Europe'),
('CZ', 'Czechia', 'Other', ''),
('DE', 'Federal Republic of Germany', 'Europe', 'Western Europe'),
('DJ', 'Republic of Djibouti', 'Africa', 'Eastern Africa'),
('DK', 'Kingdom of Denmark', 'Europe', 'Northern Europe'),
('DM', 'Commonwealth of Dominica', 'Americas', 'Caribbean'),
('DO', 'Dominican Republic', 'Americas', 'Caribbean'),
('DZ', 'People''s Democratic Republic of Algeria', 'Other', ''),
('EC', 'Republic of Ecuador', 'Americas', 'South America'),
('EE', 'Republic of Estonia', 'Europe', 'Northern Europe'),
('EG', 'Arab Republic of Egypt', 'Africa', 'Northern Africa'),
('EH', 'Western Sahara', 'Africa', 'Northern Africa'),
('ER', 'the State of Eritrea', 'Other', ''),
('ES', 'Kingdom of Spain', 'Europe', 'Southern Europe'),
('ET', 'Federal Democratic Republic of Ethiopia', 'Africa', 'Eastern Africa'),
('FI', 'Republic of Finland', 'Europe', 'Northern Europe'),
('FJ', 'Republic of Fiji', 'Oceania', 'Melanesia'),
('FK', 'Falkland Islands (Malvinas)', 'Other', ''),
('FM', 'Federated States of Micronesia', 'Oceania', 'Micronesia'),
('FO', 'Faroe Islands', 'Europe', 'Northern Europe'),
('FR', 'French Republic', 'Europe', 'Western Europe'),
('GA', 'Gabonese Republic', 'Africa', 'Middle Africa'),
('GB', 'United Kingdom of Great Britain and Northern Ireland', 'Europe', 'Northern Europe'),
('GD', 'Grenada', 'Americas', 'Caribbean'),
('GE', 'Georgia', 'Asia', 'Western Asia'),
('GF', 'French Guiana', 'Americas', 'South America'),
('GG', 'Guernsey', 'Europe', 'Northern Europe'),
('GH', 'Republic of Ghana', 'Other', ''),
('GI', 'Gibraltar', 'Europe', 'Southern Europe'),
('GL', 'Greenland', 'Americas', 'Northern America'),
('GM', 'Republic of the Gambia', 'Africa', 'Western Africa'),
('GN', 'Republic of Guinea', 'Africa', 'Western Africa'),
('GP', 'Guadeloupe', 'Americas', 'Caribbean'),
('GQ', 'Republic of Equatorial Guinea', 'Africa', 'Middle Africa'),
('GR', 'Hellenic Republic', 'Europe', 'Southern Europe'),
('GS', 'South Georgia and the South Sandwich Islands', 'Americas', 'South America'),
('GT', 'Republic of Guatemala', 'Other', ''),
('GU', 'Guam', 'Oceania', 'Micronesia'),
('GW', 'Republic of Guinea-Bissau', 'Africa', 'Western Africa'),
('GY', 'Republic of Guyana', 'Other', ''),
('HK', 'Hong Kong Special Administrative Region of China', 'Other', ''),
('HM', 'Heard Island and McDonald Islands', 'Other', ''),
('HN', 'Republic of Honduras', 'Americas', 'Central America'),
('HR', 'Republic of Croatia', 'Europe', 'Southern Europe'),
('HT', 'Republic of Haiti', 'Americas', 'Caribbean'),
('HU', 'Hungary', 'Europe', 'Eastern Europe'),
('ID', 'Republic of Indonesia', 'Asia', 'South-Eastern Asia'),
('IE', 'Ireland', 'Europe', 'Northern Europe'),
('IL', 'State of Israel', 'Asia', 'Western Asia'),
('IM', 'Isle of Man', 'Europe', 'Northern Europe'),
('IN', 'Republic of India', 'Asia', 'Southern Asia'),
('IO', 'British Indian Ocean Territory', 'Africa', 'Eastern Africa'),
('IQ', 'Republic of Iraq', 'Asia', 'Western Asia'),
('IR', 'Iran', 'Asia', 'Southern Asia'),
('IS', 'Republic of Iceland', 'Europe', 'Northern Europe'),
('IT', 'Italian Republic', 'Europe', 'Southern Europe'),
('JE', 'Jersey', 'Europe', 'Northern Europe'),
('JM', 'Jamaica', 'Americas', 'Caribbean'),
('JO', 'Hashemite Kingdom of Jordan', 'Asia', 'Western Asia'),
('JP', 'Japan', 'Asia', 'Eastern Asia'),
('KE', 'Republic of Kenya', 'Africa', 'Eastern Africa'),
('KG', 'Kyrgyz Republic', 'Asia', 'Central Asia'),
('KH', 'Kingdom of Cambodia', 'Asia', 'South-Eastern Asia'),
('KI', 'Republic of Kiribati', 'Oceania', 'Micronesia'),
('KM', 'Union of the Comoros', 'Africa', 'Eastern Africa'),
('KN', 'Saint Kitts and Nevis', 'Americas', 'Caribbean'),
('KP', 'North Korea', 'Asia', 'Eastern Asia'),
('KR', 'South Korea', 'Asia', 'Eastern Asia'),
('KW', 'State of Kuwait', 'Asia', 'Western Asia'),
('KY', 'Cayman Islands', 'Americas', 'Caribbean'),
('KZ', 'Republic of Kazakhstan', 'Asia', 'Central Asia'),
('LA', 'Laos', 'Asia', 'South-Eastern Asia'),
('LB', 'Lebanese Republic', 'Asia', 'Western Asia'),
('LC', 'Saint Lucia', 'Americas', 'Caribbean'),
('LI', 'Principality of Liechtenstein', 'Europe', 'Western Europe'),
('LK', 'Democratic Socialist Republic of Sri Lanka', 'Asia', 'Southern Asia'),
('LR', 'Republic of Liberia', 'Africa', 'Western Africa'),
('LS', 'Kingdom of Lesotho', 'Africa', 'Southern Africa'),
('LT', 'Republic of Lithuania', 'Europe', 'Northern Europe'),
('LU', 'Grand Duchy of Luxembourg', 'Europe', 'Western Europe'),
('LV', 'Republic of Latvia', 'Europe', 'Northern Europe'),
('LY', 'Libya', 'Africa', 'Northern Africa'),
('MA', 'Kingdom of Morocco', 'Africa', 'Northern Africa'),
('MC', 'Principality of Monaco', 'Europe', 'Western Europe'),
('MD', 'Moldova', 'Europe', 'Eastern Europe'),
('ME', 'Montenegro', 'Other', ''),
('MF', 'Saint Martin', 'Other', ''),
('MG', 'Republic of Madagascar', 'Africa', 'Eastern Africa'),
('MH', 'Republic of the Marshall Islands', 'Oceania', 'Micronesia'),
('MK', 'Republic of North Macedonia', 'Other', ''),
('ML', 'Republic of Mali', 'Africa', 'Western Africa'),
('MM', 'Republic of Myanmar', 'Other', ''),
('MN', 'Mongolia', 'Asia', 'Eastern Asia'),
('MO', 'Macao Special Administrative Region of China', 'Other', ''),
('MP', 'Commonwealth of the Northern Mariana Islands', 'Oceania', 'Micronesia'),
('MQ', 'Martinique', 'Americas', 'Caribbean'),
('MR', 'Islamic Republic of Mauritania', 'Africa', 'Western Africa'),
('MS', 'Montserrat', 'Americas', 'Caribbean'),
('MT', 'Republic of Malta', 'Europe', 'Southern Europe'),
('MU', 'Republic of Mauritius', 'Africa', 'Eastern Africa'),
('MV', 'Republic of Maldives', 'Other', ''),
('MW', 'Republic of Malawi', 'Africa', 'Eastern Africa'),
('MX', 'United Mexican States', 'Americas', 'Central America'),
('MY', 'Malaysia', 'Asia', 'South-Eastern Asia'),
('MZ', 'Republic of Mozambique', 'Africa', 'Eastern Africa'),
('NA', 'Republic of Namibia', 'Africa', 'Southern Africa'),
('NC', 'New Caledonia', 'Oceania', 'Melanesia'),
('NE', 'Republic of the Niger', 'Other', ''),
('NF', 'Norfolk Island', 'Oceania', 'Australia and New Zealand'),
('NG', 'Federal Republic of Nigeria', 'Africa', 'Western Africa'),
('NI', 'Republic of Nicaragua', 'Americas', 'Central America'),
('NL', 'Kingdom of the Netherlands', 'Other', ''),
('NO', 'Kingdom of Norway', 'Europe', 'Northern Europe'),
('NP', 'Federal Democratic Republic of Nepal', 'Asia', 'Southern Asia'),
('NR', 'Republic of Nauru', 'Oceania', 'Micronesia'),
('NU', 'Niue', 'Oceania', 'Polynesia'),
('NZ', 'New Zealand', 'Oceania', 'Australia and New Zealand'),
('OM', 'Sultanate of Oman', 'Asia', 'Western Asia'),
('PA', 'Republic of Panama', 'Americas', 'Central America'),
('PE', 'Republic of Peru', 'Americas', 'South America'),
('PF', 'French Polynesia', 'Oceania', 'Polynesia'),
('PG', 'Independent State of Papua New Guinea', 'Oceania', 'Melanesia'),
('PH', 'Republic of the Philippines', 'Asia', 'South-Eastern Asia'),
('PK', 'Islamic Republic of Pakistan', 'Asia', 'Southern Asia'),
('PL', 'Republic of Poland', 'Europe', 'Eastern Europe'),
('PM', 'Saint Pierre and Miquelon', 'Americas', 'Northern America'),
('PN', 'Pitcairn', 'Other', ''),
('PR', 'Puerto Rico', 'Americas', 'Caribbean'),
('PS', 'Palestine', 'Other', ''),
('PT', 'Portuguese Republic', 'Europe', 'Southern Europe'),
('PW', 'Republic of Palau', 'Oceania', 'Micronesia'),
('PY', 'Republic of Paraguay', 'Americas', 'South America'),
('QA', 'State of Qatar', 'Asia', 'Western Asia'),
('RE', 'Réunion', 'Africa', 'Eastern Africa'),
('RO', 'Romania', 'Europe', 'Eastern Europe'),
('RS', 'Republic of Serbia', 'Europe', 'Eastern Europe'),
('RU', 'Russia', 'Europe', 'Eastern Europe'),
('RW', 'Rwandese Republic', 'Other', ''),
('SA', 'Kingdom of Saudi Arabia', 'Asia', 'Western Asia'),
('SB', 'Solomon Islands', 'Oceania', 'Melanesia'),
('SC', 'Republic of Seychelles', 'Africa', 'Eastern Africa'),
('SD', 'Republic of the Sudan', 'Africa', 'Northern Africa'),
('SE', 'Kingdom of Sweden', 'Europe', 'Northern Europe'),
('SG', 'Republic of Singapore', 'Other', ''),
('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Africa', 'Western Africa'),
('SI', 'Republic of Slovenia', 'Europe', 'Southern Europe'),
('SJ', 'Svalbard and Jan Mayen', 'Europe', 'Northern Europe'),
('SK', 'Slovak Republic', 'Europe', 'Eastern Europe'),
('SL', 'Republic of Sierra Leone', 'Africa', 'Western Africa'),
('SM', 'Republic of San Marino', 'Europe', 'Southern Europe'),
('SN', 'Republic of Senegal', 'Africa', 'Western Africa'),
('SO', 'Federal Republic of Somalia', 'Africa', 'Eastern Africa'),
('SR', 'Republic of Suriname', 'Americas', 'South America'),
('SS', 'Republic of South Sudan', 'Other', ''),
('ST', 'Democratic Republic of Sao Tome and Principe', 'Other', ''),
('SV', 'Republic of El Salvador', 'Americas', 'Central America'),
('SX', 'Sint Maarten', 'Other', ''),
('SY', 'Syria', 'Asia', 'Western Asia'),
('SZ', 'Kingdom of Eswatini', 'Other', ''),
('TC', 'Turks and Caicos Islands', 'Other', ''),
('TD', 'Republic of Chad', 'Africa', 'Middle Africa'),
('TF', 'French Southern Territories', 'Other', ''),
('TG', 'Togolese Republic', 'Africa', 'Western Africa'),
('TH', 'Kingdom of Thailand', 'Asia', 'South-Eastern Asia'),
('TJ', 'Republic of Tajikistan', 'Asia', 'Central Asia'),
('TK', 'Tokelau', 'Oceania', 'Polynesia'),
('TL', 'Democratic Republic of Timor-Leste', 'Asia', 'South-Eastern Asia'),
('TM', 'Turkmenistan', 'Asia', 'Central Asia'),
('TN', 'Republic of Tunisia', 'Africa', 'Northern Africa'),
('TO', 'Kingdom of Tonga', 'Other', ''),
('TR', 'Republic of Türkiye', 'Other', ''),
('TT', 'Republic of Trinidad and Tobago', 'Americas', 'Caribbean'),
('TV', 'Tuvalu', 'Oceania', 'Polynesia'),
('TW', 'Taiwan', 'Asia', 'Eastern Asia'),
('TZ', 'Tanzania', 'Africa', 'Eastern Africa'),
('UA', 'Ukraine', 'Europe', 'Eastern Europe'),
('UG', 'Republic of Uganda', 'Africa', 'Eastern Africa'),
('UM', 'United States Minor Outlying Islands', 'Americas', 'Northern America'),
('US', 'United States of America', 'Americas', 'Northern America'),
('UY', 'Eastern Republic of Uruguay', 'Other', ''),
('UZ', 'Republic of Uzbekistan', 'Asia', 'Central Asia'),
('VA', 'Holy See (Vatican City State)', 'Other', ''),
('VC', 'Saint Vincent and the Grenadines', 'Americas', 'Caribbean'),
('VE', 'Venezuela', 'Americas', 'South America'),
('VG', 'British Virgin Islands', 'Other', ''),
('VI', 'U.S. Virgin Islands', 'Other', ''),
('VN', 'Vietnam', 'Asia', 'South-Eastern Asia'),
('VU', 'Republic of Vanuatu', 'Oceania', 'Melanesia'),
('WF', 'Wallis and Futuna', 'Oceania', 'Polynesia'),
('WS', 'Independent State of Samoa', 'Oceania', 'Polynesia'),
('XK', 'Kosovo', 'Europe', 'Southern Europe'),
('YE', 'Republic of Yemen', 'Other', ''),
('YT', 'Mayotte', 'Africa', 'Eastern Africa'),
('ZA', 'Republic of South Africa', 'Africa', 'Southern Africa'),
('ZM', 'Republic of Zambia', 'Africa', 'Eastern Africa'),
('ZW', 'Republic of Zimbabwe', 'Africa', 'Eastern Africa');

COMMIT;
SET FOREIGN_KEY_CHECKS = 1;
