<?php
session_start();
require __DIR__ . '/includes/db.php';
require __DIR__ . '/includes/functions.php';

try { handle_post_actions(); } catch (Throwable $e) { flash('error', $e->getMessage()); }
if (getv('page') === 'logout') { if(!hash_equals(csrf_token(),getv('csrf'))) { flash('error','Invalid logout link.'); redirect_to('?page=home'); } logout_user(); redirect_to('?page=home'); }
if (getv('page') === 'export') { export_module_csv(getv('module')); }
if (getv('page') === 'export_all') { export_database_zip(); }

$page = getv('page','home');
$moduleFromPage = module_key_from_page($page);
if ($moduleFromPage) { $_GET['module'] = $moduleFromPage; $page='module'; }
$valid = ['home','search','catalogue','module','detail','pricing','login','register','dashboard','answer','account','admin','contact'];
if (!in_array($page,$valid,true)) $page='home';
if ($page === 'admin' && !defined('ANGANI_ADMIN_CONTEXT')) { redirect_to('admin/?' . ($_SERVER['QUERY_STRING'] ?? '')); }
if (in_array($page, ['dashboard','answer','account'], true) && !is_logged_in()) { redirect_to('?page=login'); }
$user=current_user(); $dbError=null; $stats=[];
try { $stats=get_stats(); } catch(Throwable $e) { $dbError=$e->getMessage(); }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Angani Data — Aviation Intelligence Atlas</title><meta name="description" content="A PHP/MySQL aviation data platform for airlines, airports, aircraft, routes, infrastructure, regulatory and commercial datasets."><link rel="icon" href="assets/favicon.png" type="image/png"><link rel="stylesheet" href="css/styles.css"><script src="https://kit.fontawesome.com/c0adf715c1.js" crossorigin="anonymous"></script></head>
<body class="<?= $page==='admin'?'admin-shell-page':'' ?>"><div class="flight-grid" aria-hidden="true"></div>
<header class="site-header"><a class="brand-lockup" href="?page=home"><img src="assets/angani-logo-white.png" alt="Angani" class="brand-logo"><span><strong>Angani Data</strong><small>Aviation Intelligence Atlas</small></span></a><button class="menu-toggle" id="menuToggle" aria-expanded="false" aria-controls="mainNav">Menu</button><nav class="main-nav" id="mainNav"><a class="<?=active_page($page,'home')?>" href="?page=home"><i class="fas fa-home"></i>Overview</a><a class="<?=active_page($page,'catalogue')?>" href="?page=catalogue"><i class="fas fa-database"></i>Our Data</a><a href="?page=airlines"><i class="fas fa-plane"></i>Airlines</a><a href="?page=airports"><i class="fas fa-plane-departure"></i>Airports</a><a href="?page=aircraft"><i class="fas fa-plane"></i>Aircraft</a><a href="?page=reference"><i class="fas fa-book"></i>Reference</a><a class="<?=active_page($page,'pricing')?>" href="?page=pricing"><i class="fas fa-credit-card"></i>Pricing</a><?php if($user): ?><a class="<?=active_page($page,'dashboard')?>" href="?page=dashboard"><i class="fas fa-chart-bar"></i>Dashboard</a><?php if(is_admin()): ?><a class="<?=active_page($page,'admin')?>" href="admin/"><i class="fas fa-shield-alt"></i>Admin</a><?php endif; ?><a href="?page=account"><?=tier_badge($user)?></a><?php else: ?><a class="<?=active_page($page,'login')?>" href="?page=login"><i class="fas fa-sign-in-alt"></i>Log in</a><?php endif; ?></nav><button class="search-toggle" id="searchToggle" aria-label="Search" aria-expanded="false"><i class="fas fa-search"></i></button></header><div class="search-overlay" id="searchOverlay" hidden><form class="search-overlay-form" method="get"><input type="hidden" name="page" value="search"><input class="search-overlay-input" name="q" placeholder="Search airlines, airports, aircraft types, codes..." autocomplete="off"><button class="btn ink">Search</button></form></div>
<main id="app"><?=flash_html()?>
<?php if($dbError): ?>
<section class="view"><div class="empty-state"><h2>Database connection required</h2><p><?=e($dbError)?></p><p>Import <code>database/00_create_database.sql</code>, then <code>database/01_schema.sql</code>, then run <code>php database/import_all_seeds.php</code>.</p></div></section>
<?php elseif($page==='home'): $insights=active_insight_cards(); ?>
<section class="view home-view"><div class="hero premium-hero"><div><div class="kicker">Angani Solutions · Aviation Data Product</div><h1>Static aviation intelligence arranged for decisions.</h1><p class="lead">A serious PHP/MySQL aviation data platform for countries, airlines, airports, infrastructure, aircraft types, lessors, commercial reference, IATA/IOSA, regulatory and route intelligence.</p><div class="hero-actions"><a class="btn primary" href="?page=register">Create account</a><a class="btn secondary" href="?page=catalogue">Browse databases</a><a class="btn secondary" href="?page=pricing">View access</a></div></div><aside class="hero-panel cockpit-panel"><div class="cockpit-line"><span>ACTIVE AIRLINES</span><b class="active-pill"><?=nfmt($stats['active_airlines'])?></b></div><h2>Data product, not just CSVs.</h2><p>Admin CRUD, import/export, user tiers, drill-down pages, reference codes and source/change controls are built into the platform.</p></aside></div>
<form class="global-search-panel" method="get"><input type="hidden" name="page" value="search"><label><span>Search aviation datasets</span><input name="q" placeholder="Try: Kenya Airways, Nairobi, A320, IOSA, NDB, fare rules..."></label><button class="btn ink">Search Angani Data</button></form>
<div class="stats-grid"><?=metric_card(nfmt($stats['active_airlines']),'Active airlines',nfmt($stats['airlines']).' total')?><?=metric_card(nfmt($stats['airports']),'Airport records','Infrastructure-ready')?><?=metric_card(nfmt($stats['aircraft_types']),'Aircraft types','Specs, engines, payload')?><?=metric_card(nfmt($stats['navaids']),'Navaids','Infrastructure & AIM')?></div>
<section class="section-head"><div><div class="eyebrow">Rotating homepage intelligence</div><h2>Interesting titbits that encourage signups</h2></div><p>These cards are controlled from Admin → Homepage Insights and can be rotated without editing code.</p></section><div class="insight-grid"><?php foreach($insights as $card): $rows=run_insight_query($card['query_key']); $locked=!empty($card['required_tier_id']) && !is_logged_in(); ?><article class="insight-card <?=$locked?'locked':''?>"><div class="topline"><span class="chip gold"><?=e($card['metric_label'])?></span><?php if($locked): ?><span class="chip danger">Pro preview</span><?php endif; ?></div><h3><?=e($card['title'])?></h3><p><?=e($card['description'])?></p><?=$locked?access_gate('Sign in to unlock the detail','This card previews a paid intelligence query.','See plans'):chart_bars($rows)?></article><?php endforeach; ?></div>
<section class="section-head"><div><div class="eyebrow">Product modules</div><h2>Designed around aviation workflows</h2></div><p>Each module supports search, filtering, drill-downs, admin CRUD and CSV import/export.</p></section><div class="module-grid"><?php foreach(module_groups() as $group=>$keys): ?><article class="module-group"><h3><?=e($group)?></h3><div><?php foreach($keys as $k): $c=module_config($k); if(!$c) continue; ?><a class="module-chip" href="<?=e(module_url($k))?>"><b><?=module_icon_html($k)?></b><span><?=e($c['label'])?></span><em><?=nfmt(module_count($k))?></em></a><?php endforeach; ?></div></article><?php endforeach; ?></div></section>
<?php elseif($page==='search'): $q=getv('q'); if($q==='') redirect_to('?page=home'); $results=global_search($q); ?>
<section class="view"><section class="section-head"><div><div class="eyebrow">Global search</div><h1>Search across Angani Data</h1></div><p>Search airlines, airports, aircraft types, reference tables, infrastructure, regulatory and commercial records from one place. Pro-only records show access gates when opened.</p></section><div class="result-summary"><strong><?=nfmt(count($results))?></strong> results for <b><?=e($q)?></b></div><?=render_global_search_results($results)?></section>
<?php elseif($page==='catalogue'): ?>
<section class="view"><section class="section-head"><div><div class="eyebrow">Database catalogue</div><h1>Angani Data modules</h1></div><p>Free users see public/reference data. Pro users unlock full drill-downs and exports. Enterprise is for bulk/API access.</p></section><div class="module-grid"><?php foreach(module_groups() as $group=>$keys): ?><article class="module-group"><h3><?=e($group)?></h3><div><?php foreach($keys as $k): $c=module_config($k); if(!$c) continue; ?><a class="module-chip" href="<?=e(module_url($k))?>"><b><?=module_icon_html($k)?></b><span><?=e($c['label'])?></span><em><?=nfmt(module_count($k))?></em></a><?php endforeach; ?></div></article><?php endforeach; ?></div></section>
<?php elseif($page==='module'): $key=getv('module','airlines'); $cfg=module_config($key); ?>
<section class="view"><?php if(!$cfg): ?><div class="empty-state"><h2>Unknown database</h2></div><?php elseif(!module_allowed($cfg)): ?><?=access_gate($cfg['label'].' is a Pro dataset','Create or upgrade your account to access this database.','View pricing')?><?php else: [$records,$total]=query_module_records($cfg,24,(page_num()-1)*24); ?><section class="section-head"><div><div class="eyebrow"><?=e($cfg['tier']==='free'?'Open database':'Pro database')?></div><h1><?=e($cfg['label'])?></h1></div><p><?=nfmt($total)?> records. Admin can add/edit/import; logged-in Pro users can export filtered data.</p></section><?=render_search_bar($key,$cfg)?><?php if(in_array($cfg['card']??'', ['airline','airport','aircraft_type','lessor','country','aircraft'], true)): ?><?=render_module_cards($key,$records)?><?php else: ?><?=render_table($records,$cfg['list'],$key)?><?php endif; ?><?=paginate($total,24)?><?php endif; ?></section>
<?php elseif($page==='detail'): $key=getv('module'); $cfg=module_config($key); $idRaw=getv('id'); $idIsStr = ($key === 'countries'); $id = $idIsStr ? $idRaw : (int)$idRaw; ?>
<section class="view"><?php if(!$cfg || !$id): ?><div class="empty-state"><h2>Record not found</h2></div><?php elseif(!module_allowed($cfg)): ?><?=access_gate('Pro detail locked','Upgrade to open full records in this database.','View pricing')?><?php else: $pkCol=($key==='countries')?'iso_alpha_2':($idIsStr?'code':'id'); $r=row('SELECT * FROM `'.$cfg['table'].'` WHERE `'.$pkCol.'`=?',[$id]); if(!$r): ?><div class="empty-state"><h2>Record not found</h2></div><?php else: ?><a class="linkish" href="<?=e(module_url($key))?>">← Back to <?=e($cfg['label'])?></a><section class="record-hero"><div><div class="eyebrow"><?=e($cfg['label'])?></div><h1><?=e($r[$cfg['title']] ?? 'Record')?></h1><p><?=e($r[$cfg['subtitle']] ?? '')?></p></div><?php if(is_admin()): ?><a class="btn ink" href="?page=admin&tab=edit&module=<?=e($key)?>&id=<?=e($id)?>">Edit in Admin</a><?php endif; ?></section><?=render_detail_fields($cfg,$r,false)?><?=render_related_sections($key,$r)?><?php endif; endif; ?></section>
<?php elseif($page==='pricing'): $tiers=tier_cards(); ?>
<section class="view"><section class="section-head"><div><div class="eyebrow">Simple access model</div><h1>Three tiers only</h1></div><p>Free for discovery, Pro for paid intelligence, Enterprise for custom/API/bulk work.</p></section><div class="pricing-grid"><?php foreach($tiers as $tier): ?><article class="pricing-card <?=$tier['code']==='pro'?'featured':''?>"><div class="topline"><span class="chip gold"><?=e($tier['name'])?></span><span class="chip"><?= $tier['code']==='enterprise'?'Contact us':'$'.e($tier['monthly_usd']).'/mo' ?></span></div><h3><?=e($tier['name'])?></h3><p><?=e($tier['description'])?></p><div class="price"><?= $tier['code']==='enterprise'?'Custom':'$'.e($tier['monthly_usd']).'<small>/month</small>' ?></div><ul><?php foreach(tier_features((int)$tier['id']) as $f): ?><li><?=e($f['feature_label'])?></li><?php endforeach; ?></ul><a class="btn <?=$tier['code']==='pro'?'primary':'ghost'?>" href="<?=$tier['code']==='enterprise'?'?page=contact':'?page=register'?>"><?=$tier['code']==='enterprise'?'Contact us':'Start '.$tier['name']?></a></article><?php endforeach; ?></div></section>
<?php elseif($page==='login'): ?>
<section class="auth-shell"><div class="panel auth-card"><div class="eyebrow">Member access</div><h1>Log in</h1><p class="muted">Demo admin: <code>admin@angani.co.uk</code> / <code>Angani@2026</code></p><form method="post" class="stack-form"><?=csrf_field()?><input type="hidden" name="action" value="login"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="btn ink" type="submit">Log in</button></form><p>New user? <a class="linkish" href="?page=register">Create account</a></p></div></section>
<?php elseif($page==='register'): ?>
<section class="auth-shell"><div class="panel auth-card"><div class="eyebrow">Create account</div><h1>Start exploring</h1><form method="post" class="stack-form"><?=csrf_field()?><input type="hidden" name="action" value="register"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="8" required></label><button class="btn ink" type="submit">Create account</button></form></div></section>
<?php elseif($page==='account'): if(!$user) redirect_to('?page=login'); ?>
<section class="view"><section class="section-head"><div><div class="eyebrow">Account</div><h1><?=e($user['name'])?></h1></div><?=tier_badge($user)?></section><div class="panel-grid"><div class="panel"><h3>Profile</h3><form method="post" class="stack-form"><?=csrf_field()?><input type="hidden" name="action" value="update_account"><label>Name<input name="name" value="<?=e($user['name'])?>"></label><label>Email<input value="<?=e($user['email'])?>" disabled></label><button class="btn ink">Save</button></form></div><div class="panel"><h3>Access</h3><p>Your current tier is <strong><?=e($user['tier_name'])?></strong>.</p><p>CSV exports and full drilldowns are available on Pro and Enterprise.</p><a class="btn primary" href="?page=pricing">Compare plans</a></div></div></section>
<?php elseif($page==='dashboard'): if(!$user) redirect_to('?page=login'); $presets=question_presets(); $dashInsights=active_insight_cards(); ?>
<section class="view"><section class="dashboard-hero panel dark"><div><div class="eyebrow">Member cockpit</div><h1>Welcome, <?=e($user['name'])?></h1><p>Use preset questions, global search and database drill-downs to turn the aviation datasets into answers.</p></div><div class="stats-grid compact"><?=metric_card(nfmt($stats['airlines']),'Airlines',nfmt($stats['active_airlines']).' active')?><?=metric_card(nfmt($stats['airports']),'Airports','global coverage')?><?=metric_card(nfmt($stats['aircraft_types']),'Aircraft types','technical intelligence')?><?=metric_card(nfmt($stats['dataset_files']),'Dataset files','source warehouse')?></div></section><form class="global-search-panel standalone" method="get"><input type="hidden" name="page" value="search"><label><span>Search your aviation data</span><input name="q" placeholder="Search across airlines, airports, aircraft types, routes, standards..."></label><button class="btn ink">Search</button><a class="btn ghost" href="?page=catalogue">Browse catalogue</a></form><section class="section-head"><div><div class="eyebrow">Preset intelligence questions</div><h1>Ask the dataset</h1></div><p>These are controlled from Admin → Preset Questions and are designed to guide logged-in users toward useful answers.</p></section><div class="question-grid"><?php foreach($presets as $q): $locked=!empty($q['required_tier_order']) && tier_order_for()< (int)$q['required_tier_order'] && !is_admin(); ?><article class="question-card"><span class="chip"><?=e($q['category'])?></span><h3><?=e($q['title'])?></h3><p><?=e($q['question_text'])?></p><?php if($locked): ?><a class="btn ghost" href="?page=pricing">Upgrade to <?=e($q['required_tier_name'])?></a><?php else: ?><a class="btn primary" href="?page=answer&q=<?=e($q['answer_key'])?>">Run question</a><?php endif; ?></article><?php endforeach; ?></div><section class="section-head"><div><div class="eyebrow">Live titbits</div><h2>Charts from current data</h2></div><p>The same insight engine powers public teasers and logged-in analysis cards.</p></section><div class="insight-grid"><?php foreach(array_slice($dashInsights,0,6) as $card): $rows=run_insight_query($card['query_key']); ?><article class="insight-card"><div class="topline"><span class="chip gold"><?=e($card['metric_label'])?></span></div><h3><?=e($card['title'])?></h3><p><?=e($card['description'])?></p><?=chart_bars($rows)?></article><?php endforeach; ?></div></section>
<?php elseif($page==='answer'): if(!$user) redirect_to('?page=login'); $answerKey=getv('q'); $preset=preset_for_answer_key($answerKey); if($preset && !preset_allowed($preset)): ?><?=access_gate('Pro question locked','Upgrade to run this preset intelligence question.','View pricing')?><?php else: $rows=run_preset_query($answerKey); ?>
<section class="view"><a class="linkish" href="?page=dashboard">← Back to questions</a><section class="section-head"><div><div class="eyebrow">Preset answer</div><h1><?=e($preset['title'] ?? labelize($answerKey))?></h1></div><a class="btn ghost" href="?page=catalogue">Open datasets</a></section><?=render_answer_visual($answerKey,$rows)?><?=render_table($rows,$rows?array_keys($rows[0]):[],null)?></section><?php endif; ?>
<?php elseif($page==='admin'): if(!is_admin()): ?><?=access_gate('Admin access required','Log in with an administrator account to manage records, imports, exports and users.','Log in')?><?php else: render_admin_page(); endif; ?>
<?php elseif($page==='contact'): ?>
<section class="view"><div class="panel contact-panel"><div class="eyebrow">Enterprise package</div><h1>Contact Angani Solutions</h1><p>For bulk exports, API access, private dashboards, custom aviation datasets and advisory work.</p><p><strong>Silas Savali</strong><br>Angani Solutions<br><a href="mailto:info@angani.co.uk">info@angani.co.uk</a><br><a href="https://www.angani.co.uk">www.angani.co.uk</a></p></div></section>
<?php endif; ?></main><footer class="site-footer"><span>Angani Data</span><span>Built for aviation professionals, consultants, airports, airlines and regulators.</span></footer><script src="js/app.js"></script></body></html>
<?php
require_once __DIR__ . '/includes/admin_render.php';
?>
