<?php
session_start();
require __DIR__ . '/includes/db.php';
require __DIR__ . '/includes/functions.php';

try { handle_post_actions(); } catch (Throwable $e) { flash('error', $e->getMessage()); }
if (getv('page') === 'logout') { if(!hash_equals(csrf_token(),getv('csrf'))) { flash('error','Invalid logout link.'); redirect_to('?page=home'); } logout_user(); redirect_to('?page=home'); }
if (getv('page') === 'export') { export_module_csv(getv('module')); }
if (getv('page') === 'export_all') { export_database_zip(); }

$page = getv('page','home');
$moduleFromPage = module_key_from_page($page);
if ($moduleFromPage) { $_GET['module'] = $moduleFromPage; $page='module'; }
$valid = ['home','search','catalogue','module','detail','pricing','login','register','dashboard','answer','account','admin','contact'];
if (!in_array($page,$valid,true)) $page='home';
if ($page === 'admin' && !defined('ANGANI_ADMIN_CONTEXT')) { redirect_to('admin/?' . ($_SERVER['QUERY_STRING'] ?? '')); }
if (in_array($page, ['dashboard','answer','account'], true) && !is_logged_in()) { redirect_to('?page=login'); }
$user=current_user(); $dbError=null; $stats=[];
try { $stats=get_stats(); } catch(Throwable $e) { $dbError=$e->getMessage(); }
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Angani Data — Aviation Intelligence Atlas</title><meta name="description" content="A PHP/MySQL aviation data platform for airlines, airports, aircraft, routes, infrastructure, regulatory and commercial datasets."><link rel="icon" href="assets/favicon.png" type="image/png"><link rel="stylesheet" href="css/styles.css"><script src="https://kit.fontawesome.com/c0adf715c1.js" crossorigin="anonymous"></script></head>
<body class="<?= $page==='admin'?'admin-shell-page':'' ?>"><div class="flight-grid" aria-hidden="true"></div>
<header class="site-header"><a class="brand-lockup" href="?page=home"><img src="assets/angani-logo-white.png" alt="Angani" class="brand-logo"><span><strong>Angani Data</strong><small>Aviation Intelligence Atlas</small></span></a><button class="menu-toggle" id="menuToggle" aria-expanded="false" aria-controls="mainNav">Menu</button><nav class="main-nav" id="mainNav"><a class="<?=active_page($page,'home')?>" href="?page=home"><i class="fas fa-home"></i>Overview</a><a class="<?=active_page($page,'catalogue')?>" href="?page=catalogue"><i class="fas fa-database"></i>Our Data</a><a href="?page=airlines"><i class="fas fa-plane"></i>Airlines</a><a href="?page=airports"><i class="fas fa-plane-departure"></i>Airports</a><a href="?page=aircraft"><i class="fas fa-plane"></i>Aircraft</a><a href="?page=reference"><i class="fas fa-book"></i>Reference</a><a class="<?=active_page($page,'pricing')?>" href="?page=pricing"><i class="fas fa-credit-card"></i>Pricing</a><?php if($user): ?><a class="<?=active_page($page,'dashboard')?>" href="?page=dashboard"><i class="fas fa-chart-bar"></i>Dashboard</a><?php if(is_admin()): ?><a class="<?=active_page($page,'admin')?>" href="admin/"><i class="fas fa-shield-alt"></i>Admin</a><?php endif; ?><a href="?page=account"><?=tier_badge($user)?></a><?php else: ?><a class="<?=active_page($page,'login')?>" href="?page=login"><i class="fas fa-sign-in-alt"></i>Log in</a><?php endif; ?></nav><button class="search-toggle" id="searchToggle" aria-label="Search" aria-expanded="false"><i class="fas fa-search"></i></button></header><div class="search-overlay" id="searchOverlay" hidden><form class="search-overlay-form" method="get"><input type="hidden" name="page" value="search"><input class="search-overlay-input" name="q" placeholder="Search airlines, airports, aircraft types, codes..." autocomplete="off"><button class="btn ink">Search</button></form></div>
<main id="app"><?=flash_html()?>
<?php if($dbError): ?>
<section class="view"><div class="empty-state"><h2>Database connection required</h2><p><?=e($dbError)?></p><p>Import <code>database/00_create_database.sql</code>, then <code>database/01_schema.sql</code>, then run <code>php database/import_all_seeds.php</code>.</p></div></section>
<?php elseif($page==='home'): $insights=active_insight_cards(); ?>
<section class="view home-view"><div class="hero premium-hero"><div><div class="kicker">Angani Solutions · Aviation Data Product</div><h1>Static aviation intelligence arranged for decisions.</h1><p class="lead">A serious PHP/MySQL aviation data platform for countries, airlines, airports, infrastructure, aircraft types, lessors, commercial reference, IATA/IOSA, regulatory and route intelligence.</p><div class="hero-actions"><a class="btn primary" href="?page=register">Create account</a><a class="btn secondary" href="?page=catalogue">Browse databases</a><a class="btn secondary" href="?page=pricing">View access</a></div></div><aside class="hero-panel cockpit-panel"><div class="cockpit-line"><span>ACTIVE AIRLINES</span><b class="active-pill"><?=nfmt($stats['active_airlines'])?></b></div><h2>Data product, not just CSVs.</h2><p>Admin CRUD, import/export, user tiers, drill-down pages, reference codes and source/change controls are built into the platform.</p></aside></div>
<form class="global-search-panel" method="get"><input type="hidden" name="page" value="search"><label><span>Search aviation datasets</span><input name="q" placeholder="Try: Kenya Airways, Nairobi, A320, IOSA, NDB, fare rules..."></label><button class="btn ink">Search Angani Data</button></form>
<div class="stats-grid"><?=metric_card(nfmt($stats['active_airlines']),'Active airlines',nfmt($stats['airlines']).' total')?><?=metric_card(nfmt($stats['airports']),'Airport records','Infrastructure-ready')?><?=metric_card(nfmt($stats['aircraft_types']),'Aircraft types','Specs, engines, payload')?><?=metric_card(nfmt($stats['navaids']),'Navaids','Infrastructure & AIM')?></div>
<section class="section-head"><div><div class="eyebrow">Rotating homepage intelligence</div><h2>Interesting titbits that encourage signups</h2></div><p>These cards are controlled from Admin → Homepage Insights and can be rotated without editing code.</p></section><div class="insight-grid"><?php foreach($insights as $card): $rows=run_insight_query($card['query_key']); $locked=!empty($card['required_tier_id']) && !is_logged_in(); ?><article class="insight-card <?=$locked?'locked':''?>"><div class="topline"><span class="chip gold"><?=e($card['metric_label'])?></span><?php if($locked): ?><span class="chip danger">Pro preview</span><?php endif; ?></div><h3><?=e($card['title'])?></h3><p><?=e($card['description'])?></p><?=$locked?access_gate('Sign in to unlock the detail','This card previews a paid intelligence query.','See plans'):chart_bars($rows)?></article><?php endforeach; ?></div>
<section class="section-head"><div><div class="eyebrow">Product modules</div><h2>Designed around aviation workflows</h2></div><p>Each module supports search, filtering, drill-downs, admin CRUD and CSV import/export.</p></section><div class="module-grid"><?php foreach(module_groups() as $group=>$keys): ?><article class="module-group"><h3><?=e($group)?></h3><div><?php foreach($keys as $k): $c=module_config($k); if(!$c) continue; ?><a class="module-chip" href="<?=e(module_url($k))?>"><b><?=module_icon_html($k)?></b><span><?=e($c['label'])?></span><em><?=nfmt(module_count($k))?></em></a><?php endforeach; ?></div></article><?php endforeach; ?></div></section>
<?php elseif($page==='search'): $q=getv('q'); if($q==='') redirect_to('?page=home'); $results=global_search($q); ?>
<section class="view"><section class="section-head"><div><div class="eyebrow">Global search</div><h1>Search across Angani Data</h1></div><p>Search airlines, airports, aircraft types, reference tables, infrastructure, regulatory and commercial records from one place. Pro-only records show access gates when opened.</p></section><div class="result-summary"><strong><?=nfmt(count($results))?></strong> results for <b><?=e($q)?></b></div><?=render_global_search_results($results)?></section>
<?php elseif($page==='catalogue'): ?>
<section class="view"><section class="section-head"><div><div class="eyebrow">Database catalogue</div><h1>Angani Data modules</h1></div><p>Free users see public/reference data. Pro users unlock full drill-downs and exports. Enterprise is for bulk/API access.</p></section><div class="module-grid"><?php foreach(module_groups() as $group=>$keys): ?><article class="module-group"><h3><?=e($group)?></h3><div><?php foreach($keys as $k): $c=module_config($k); if(!$c) continue; ?><a class="module-chip" href="<?=e(module_url($k))?>"><b><?=module_icon_html($k)?></b><span><?=e($c['label'])?></span><em><?=nfmt(module_count($k))?></em></a><?php endforeach; ?></div></article><?php endforeach; ?></div></section>
<?php elseif($page==='module'): $key=getv('module','airlines'); $cfg=module_config($key); ?>
<section class="view"><?php if(!$cfg): ?><div class="empty-state"><h2>Unknown database</h2></div><?php elseif(!module_allowed($cfg)): ?><?=access_gate($cfg['label'].' is a Pro dataset','Create or upgrade your account to access this database.','View pricing')?><?php else: [$records,$total]=query_module_records($cfg,24,(page_num()-1)*24); ?><section class="section-head"><div><div class="eyebrow"><?=e($cfg['tier']==='free'?'Open database':'Pro database')?></div><h1><?=e($cfg['label'])?></h1></div><p><?=nfmt($total)?> records. Admin can add/edit/import; logged-in Pro users can export filtered data.</p></section><?=render_search_bar($key,$cfg)?><?php if(in_array($cfg['card']??'', ['airline','airport','aircraft_type','lessor','country','aircraft'], true)): ?><?=render_module_cards($key,$records)?><?php else: ?><?=render_table($records,$cfg['list'],$key)?><?php endif; ?><?=paginate($total,24)?><?php endif; ?></section>
<?php elseif($page==='detail'): $key=getv('module'); $cfg=module_config($key); $idRaw=getv('id'); $idIsStr = ($key === 'countries'); $id = $idIsStr ? $idRaw : (int)$idRaw; ?>
<section class="view"><?php if(!$cfg || !$id): ?><div class="empty-state"><h2>Record not found</h2></div><?php elseif(!module_allowed($cfg)): ?><?=access_gate('Pro detail locked','Upgrade to open full records in this database.','View pricing')?><?php else: $pkCol=($key==='countries')?'iso_alpha_2':($idIsStr?'code':'id'); $r=row('SELECT * FROM `'.$cfg['table'].'` WHERE `'.$pkCol.'`=?',[$id]); if(!$r): ?><div class="empty-state"><h2>Record not found</h2></div><?php else: ?><a class="linkish" href="<?=e(module_url($key))?>">← Back to <?=e($cfg['label'])?></a><section class="record-hero"><div><div class="eyebrow"><?=e($cfg['label'])?></div><h1><?=e($r[$cfg['title']] ?? 'Record')?></h1><p><?=e($r[$cfg['subtitle']] ?? '')?></p></div><?php if(is_admin()): ?><a class="btn ink" href="?page=admin&tab=edit&module=<?=e($key)?>&id=<?=e($id)?>">Edit in Admin</a><?php endif; ?></section><?=render_detail_fields($cfg,$r,false)?><?=render_related_sections($key,$r)?><?php endif; endif; ?></section>
<?php elseif($page==='pricing'): $tiers=tier_cards(); ?>
<section class="view"><section class="section-head"><div><div class="eyebrow">Simple access model</div><h1>Three tiers only</h1></div><p>Free for discovery, Pro for paid intelligence, Enterprise for custom/API/bulk work.</p></section><div class="pricing-grid"><?php foreach($tiers as $tier): ?><article class="pricing-card <?=$tier['code']==='pro'?'featured':''?>"><div class="topline"><span class="chip gold"><?=e($tier['name'])?></span><span class="chip"><?= $tier['code']==='enterprise'?'Contact us':'$'.e($tier['monthly_usd']).'/mo' ?></span></div><h3><?=e($tier['name'])?></h3><p><?=e($tier['description'])?></p><div class="price"><?= $tier['code']==='enterprise'?'Custom':'$'.e($tier['monthly_usd']).'<small>/month</small>' ?></div><ul><?php foreach(tier_features((int)$tier['id']) as $f): ?><li><?=e($f['feature_label'])?></li><?php endforeach; ?></ul><a class="btn <?=$tier['code']==='pro'?'primary':'ghost'?>" href="<?=$tier['code']==='enterprise'?'?page=contact':'?page=register'?>"><?=$tier['code']==='enterprise'?'Contact us':'Start '.$tier['name']?></a></article><?php endforeach; ?></div></section>
<?php elseif($page==='login'): ?>
<section class="auth-shell"><div class="panel auth-card"><div class="eyebrow">Member access</div><h1>Log in</h1><p class="muted">Demo admin: <code>admin@angani.co.uk</code> / <code>Angani@2026</code></p><form method="post" class="stack-form"><?=csrf_field()?><input type="hidden" name="action" value="login"><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" required></label><button class="btn ink" type="submit">Log in</button></form><p>New user? <a class="linkish" href="?page=register">Create account</a></p></div></section>
<?php elseif($page==='register'): ?>
<section class="auth-shell"><div class="panel auth-card"><div class="eyebrow">Create account</div><h1>Start exploring</h1><form method="post" class="stack-form"><?=csrf_field()?><input type="hidden" name="action" value="register"><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Password<input name="password" type="password" minlength="8" required></label><button class="btn ink" type="submit">Create account</button></form></div></section>
<?php elseif($page==='account'): if(!$user) redirect_to('?page=login'); ?>
<section class="view"><section class="section-head"><div><div class="eyebrow">Account</div><h1><?=e($user['name'])?></h1></div><?=tier_badge($user)?></section><div class="panel-grid"><div class="panel"><h3>Profile</h3><form method="post" class="stack-form"><?=csrf_field()?><input type="hidden" name="action" value="update_account"><label>Name<input name="name" value="<?=e($user['name'])?>"></label><label>Email<input value="<?=e($user['email'])?>" disabled></label><button class="btn ink">Save</button></form></div><div class="panel"><h3>Access</h3><p>Your current tier is <strong><?=e($user['tier_name'])?></strong>.</p><p>CSV exports and full drilldowns are available on Pro and Enterprise.</p><a class="btn primary" href="?page=pricing">Compare plans</a></div></div></section>
<?php elseif($page==='dashboard'): if(!$user) redirect_to('?page=login'); $presets=question_presets(); $dashInsights=active_insight_cards(); ?>
<section class="view"><section class="dashboard-hero panel dark"><div><div class="eyebrow">Member cockpit</div><h1>Welcome, <?=e($user['name'])?></h1><p>Use preset questions, global search and database drill-downs to turn the aviation datasets into answers.</p></div><div class="stats-grid compact"><?=metric_card(nfmt($stats['airlines']),'Airlines',nfmt($stats['active_airlines']).' active')?><?=metric_card(nfmt($stats['airports']),'Airports','global coverage')?><?=metric_card(nfmt($stats['aircraft_types']),'Aircraft types','technical intelligence')?><?=metric_card(nfmt($stats['dataset_files']),'Dataset files','source warehouse')?></div></section><form class="global-search-panel standalone" method="get"><input type="hidden" name="page" value="search"><label><span>Search your aviation data</span><input name="q" placeholder="Search across airlines, airports, aircraft types, routes, standards..."></label><button class="btn ink">Search</button><a class="btn ghost" href="?page=catalogue">Browse catalogue</a></form><section class="section-head"><div><div class="eyebrow">Preset intelligence questions</div><h1>Ask the dataset</h1></div><p>These are controlled from Admin → Preset Questions and are designed to guide logged-in users toward useful answers.</p></section><div class="question-grid"><?php foreach($presets as $q): $locked=!empty($q['required_tier_order']) && tier_order_for()< (int)$q['required_tier_order'] && !is_admin(); ?><article class="question-card"><span class="chip"><?=e($q['category'])?></span><h3><?=e($q['title'])?></h3><p><?=e($q['question_text'])?></p><?php if($locked): ?><a class="btn ghost" href="?page=pricing">Upgrade to <?=e($q['required_tier_name'])?></a><?php else: ?><a class="btn primary" href="?page=answer&q=<?=e($q['answer_key'])?>">Run question</a><?php endif; ?></article><?php endforeach; ?></div><section class="section-head"><div><div class="eyebrow">Live titbits</div><h2>Charts from current data</h2></div><p>The same insight engine powers public teasers and logged-in analysis cards.</p></section><div class="insight-grid"><?php foreach(array_slice($dashInsights,0,6) as $card): $rows=run_insight_query($card['query_key']); ?><article class="insight-card"><div class="topline"><span class="chip gold"><?=e($card['metric_label'])?></span></div><h3><?=e($card['title'])?></h3><p><?=e($card['description'])?></p><?=chart_bars($rows)?></article><?php endforeach; ?></div></section>
<?php elseif($page==='answer'): if(!$user) redirect_to('?page=login'); $answerKey=getv('q'); $preset=preset_for_answer_key($answerKey); if($preset && !preset_allowed($preset)): ?><?=access_gate('Pro question locked','Upgrade to run this preset intelligence question.','View pricing')?><?php else: $rows=run_preset_query($answerKey); ?>
<section class="view"><a class="linkish" href="?page=dashboard">← Back to questions</a><section class="section-head"><div><div class="eyebrow">Preset answer</div><h1><?=e($preset['title'] ?? labelize($answerKey))?></h1></div><a class="btn ghost" href="?page=catalogue">Open datasets</a></section><?=render_answer_visual($answerKey,$rows)?><?=render_table($rows,$rows?array_keys($rows[0]):[],null)?></section><?php endif; ?>
<?php elseif($page==='admin'): if(!is_admin()): ?><?=access_gate('Admin access required','Log in with an administrator account to manage records, imports, exports and users.','Log in')?><?php else: render_admin_page(); endif; ?>
<?php elseif($page==='contact'): ?>
<section class="view"><div class="panel contact-panel"><div class="eyebrow">Enterprise package</div><h1>Contact Angani Solutions</h1><p>For bulk exports, API access, private dashboards, custom aviation datasets and advisory work.</p><p><strong>Silas Savali</strong><br>Angani Solutions<br><a href="mailto:info@angani.co.uk">info@angani.co.uk</a><br><a href="https://www.angani.co.uk">www.angani.co.uk</a></p></div></section>
<?php endif; ?></main><footer class="site-footer"><span>Angani Data</span><span>Built for aviation professionals, consultants, airports, airlines and regulators.</span></footer><script src="js/app.js"></script></body></html>
<?php
function admin_metric(string $label, $value, string $note='', string $tone=''): string {
    return '<article class="admin-kpi '.$tone.'"><span>'.e($label).'</span><strong>'.e(nfmt($value)).'</strong>'.($note?'<small>'.e($note).'</small>':'').'</article>';
}
function admin_safe_count(string $sql, array $params=[]): int { try{return (int)scalar($sql,$params);}catch(Throwable $e){return 0;} }
function admin_empty_modules(): array { $out=[]; foreach(modules() as $k=>$c){ if(module_count($k)===0) $out[$k]=$c; } return $out; }
function admin_module_nav(string $current='airlines'): string {
    $html='<div class="admin-module-nav">';
    foreach(module_groups() as $group=>$keys){
        $open=in_array($current,$keys,true)?' open':'';
        $html.='<details'.$open.'><summary>'.e($group).'</summary>';
        foreach($keys as $k){ $c=module_config($k); if(!$c) continue; $html.='<a class="'.($k===$current?'active':'').'" href="?page=admin&tab=records&module='.e($k).'">'.e($c['label']).' <small>'.nfmt(module_count($k)).'</small></a>'; }
        $html.='</details>';
    }
    return $html.'</div>';
}
function admin_search_bar(string $module, array $cfg): string {
    return '<form method="get" class="toolbar admin-toolbar"><input type="hidden" name="page" value="admin"><input type="hidden" name="tab" value="records"><input type="hidden" name="module" value="'.e($module).'"><label class="searchbox"><span>Search records</span><input name="q" value="'.e(getv('q')).'" placeholder="Search '.e($cfg['label']).'"></label><label class="searchbox small"><span>Country</span>'.country_select('country',getv('country')).'</label><button class="btn ink">Apply filters</button><a class="btn ghost" href="?page=admin&tab=records&module='.e($module).'">Reset</a><a class="btn ghost" href="?page=export&module='.e($module).'&'.e(http_build_query(['q'=>getv('q'),'country'=>getv('country')])).'">Export filtered CSV</a></form>';
}
function render_admin_page(): void {
    $tab=getv('tab','overview'); $module=getv('module','airlines'); $cfg=module_config($module);
    $nav=[
        'overview'=>'Command Center',
        'records'=>'Records & CRUD',
        'pipeline'=>'Data Pipeline',
        'imports'=>'Imports / Exports',
        'quality'=>'Data Quality',
        'users'=>'Users',
        'plans'=>'Plans & Access',
        'questions'=>'Preset Questions',
        'insights'=>'Homepage Insights',
        'tasks'=>'100% Tasks'
    ];
    echo '<section class="admin-layout"><aside class="admin-side"><div class="admin-logo"><span>AD</span><div><h2>Admin Console</h2><p>Operational backend</p></div></div><nav class="admin-side-nav">';
    foreach($nav as $key=>$label){ echo '<a class="'.($tab===$key?'active':'').'" href="?page=admin&tab='.e($key).($key==='records'?'&module=airlines':'').'">'.e($label).'</a>'; }
    echo '</nav><div class="admin-side-foot"><small>Public frontend is separate from this console. Admin screens expose actions; public screens expose aviation intelligence.</small></div></aside><section class="admin-main">';
    if($tab==='overview') render_admin_overview();
    elseif($tab==='users') render_admin_users();
    elseif($tab==='plans') render_admin_plans();
    elseif($tab==='questions') render_admin_questions();
    elseif($tab==='insights') render_admin_insights();
    elseif($tab==='imports') render_admin_imports();
    elseif($tab==='quality') render_admin_quality();
    elseif($tab==='tasks') render_admin_tasks();
    elseif($tab==='pipeline') render_admin_pipeline();
    elseif($tab==='edit') render_admin_edit($module,getv('id'));
    else render_admin_records($module,$cfg);
    echo '</section></section>';
}
function render_admin_overview(): void {
    $s=get_stats(); $needs=admin_safe_count("SELECT COUNT(*) FROM staging_import_records WHERE status IN ('pending','needs_review','conflict')"); $bad=admin_safe_count("SELECT COUNT(*) FROM import_batches WHERE status IN ('failed','needs_review')"); $exports=admin_safe_count('SELECT COUNT(*) FROM export_logs'); $done=admin_safe_count("SELECT COUNT(*) FROM admin_tasks WHERE status='done'");
    echo '<div class="admin-head"><div><div class="eyebrow">Operations</div><h1>Admin Command Center</h1><p>Manage the data product, users, imports, quality review and homepage intelligence from one backend.</p></div><div class="hero-actions"><a class="btn primary" href="?page=admin&tab=records&module=airlines">Manage Records</a><a class="btn ghost" href="?page=admin&tab=imports">Import / Export</a></div></div>';
    echo '<div class="admin-kpi-grid">'.admin_metric('Airlines',$s['airlines'],nfmt($s['active_airlines']).' active','success').admin_metric('Airports',$s['airports'],'Infrastructure ready').admin_metric('Aircraft Types',$s['aircraft_types'],'Specs & type data').admin_metric('Users',$s['users'],'Accounts').admin_metric('Staging Review',$needs,'Rows needing attention',$needs?'warning':'success').admin_metric('Import Issues',$bad,'Batches to inspect',$bad?'danger':'success').admin_metric('Exports',$exports,'Logged downloads').admin_metric('Tasks Done',$done,'Readiness checklist').'</div>';
    echo '<div class="admin-action-grid"><article class="admin-action-card"><h3>Records</h3><p>Add, edit, preview and delete records across every configured aviation database.</p><a class="btn ink" href="?page=admin&tab=records&module=airlines">Open CRUD</a></article><article class="admin-action-card"><h3>Imports & Exports</h3><p>Append/truncate-import CSVs, export filtered module records, or export the whole database as CSV ZIP.</p><a class="btn ink" href="?page=admin&tab=imports">Open data ops</a></article><article class="admin-action-card"><h3>Data Quality</h3><p>Review staging rows, import batches, export logs and empty modules before launch.</p><a class="btn ink" href="?page=admin&tab=quality">Review quality</a></article><article class="admin-action-card"><h3>Users & Plans</h3><p>Manage users, roles, statuses and the simplified Free / Pro / Enterprise access model.</p><a class="btn ink" href="?page=admin&tab=users">Manage users</a></article></div>';
    echo '<section class="panel"><div class="topline"><h3>Database modules</h3><a class="btn mini ghost" href="?page=admin&tab=quality">View empty modules</a></div><div class="module-grid compact">';
    foreach(module_groups() as $group=>$keys){ echo '<article class="module-group"><h3>'.e($group).'</h3><div>'; foreach($keys as $k){ $c=module_config($k); if($c) echo '<a class="module-chip" href="?page=admin&tab=records&module='.e($k).'"><b>'.module_icon_html($k).'</b><span>'.e($c['label']).'</span><em>'.nfmt(module_count($k)).'</em></a>'; } echo '</div></article>'; }
    echo '</div></section>';
}
function render_admin_records(string $module, ?array $cfg): void {
    if(!$cfg){echo '<div class="empty-state"><h2>Unknown module</h2></div>';return;}
    [$records,$total]=query_module_records($cfg,30,(page_num()-1)*30);
    echo '<div class="admin-head"><div><div class="eyebrow">Records & CRUD</div><h1>'.e($cfg['label']).'</h1><p>'.nfmt($total).' records · table <code>'.e($cfg['table']).'</code></p></div><div class="hero-actions"><a class="btn primary" href="?page=admin&tab=edit&module='.e($module).'">Add record</a><a class="btn ghost" href="?page=admin&tab=imports&module='.e($module).'">Import CSV</a><a class="btn ghost" href="?page=export&module='.e($module).'&'.e(http_build_query(['q'=>getv('q'),'country'=>getv('country')])).'">Export CSV</a></div></div>';
    echo admin_module_nav($module).admin_search_bar($module,$cfg).'<div class="admin-note"><strong>Admin mode:</strong> record actions are explicit here. Public users see clean database pages with internal IDs/source/import fields hidden.</div>'.render_admin_record_table($records,$cfg['list'],$module).paginate($total,30);
}
function render_admin_edit(string $module,string $id=''): void {
    $cfg=module_config($module); if(!$cfg){echo '<div class="empty-state"><h2>Unknown module</h2></div>';return;} $pk=module_pk($module); $r=$id!==''?row('SELECT * FROM `'.$cfg['table'].'` WHERE `'.$pk.'`=?',[$id]):[];
    echo '<div class="admin-head"><div><div class="eyebrow">'.($id?'Edit record':'Add record').'</div><h1>'.e($cfg['label']).'</h1><p>Only the editable business fields are shown. Internal IDs and import/source fields remain system-managed.</p></div><div class="hero-actions"><a class="btn ghost" href="?page=admin&tab=records&module='.e($module).'">Back to records</a>'.($id?'<a class="btn ghost" href="'.e(detail_url($module,$id)).'">Preview public detail</a>':'').'</div></div>';
    echo '<form method="post" class="admin-form">'.csrf_field().'<input type="hidden" name="action" value="admin_save_record"><input type="hidden" name="module" value="'.e($module).'"><input type="hidden" name="id" value="'.e($id).'">';
    foreach($cfg['fields'] as $f){ $val=$r[$f] ?? ''; $isText=str_contains($f,'description')||str_contains($f,'notes')||str_contains($f,'story')||str_contains($f,'text')||str_contains($f,'summary')||str_contains($f,'requirements')||str_contains($f,'url')||str_contains($f,'source')||str_contains($f,'history')||str_contains($f,'milestones')||str_contains($f,'json'); echo '<label><span>'.e(labelize($f)).'</span>'; if($isText) echo '<textarea name="'.e($f).'" rows="4">'.e($val).'</textarea>'; else echo '<input name="'.e($f).'" value="'.e($val).'">'; echo '</label>'; }
    echo '<div class="form-actions"><button class="btn ink">Save record</button></div></form>';
    if($id!==''){ echo '<details class="admin-danger-zone"><summary>Danger zone</summary><form method="post" onsubmit="return confirm(\'Delete this record permanently?\')">'.csrf_field().'<input type="hidden" name="action" value="admin_delete_record"><input type="hidden" name="module" value="'.e($module).'"><input type="hidden" name="id" value="'.e($id).'"><button class="btn danger">Delete record</button></form></details>'; }
}
function render_admin_users(): void {
    $tiers=tier_cards(); $q=getv('q'); $params=[]; $where=''; if($q!==''){ $where='WHERE u.name LIKE ? OR u.email LIKE ? OR u.role LIKE ? OR u.status LIKE ?'; $params=['%'.$q.'%','%'.$q.'%','%'.$q.'%','%'.$q.'%']; }
    $users=rows('SELECT u.*, st.name tier_name FROM users u LEFT JOIN subscription_tiers st ON st.id=u.tier_id '.$where.' ORDER BY u.created_at DESC LIMIT 200',$params);
    echo '<div class="admin-head"><div><div class="eyebrow">Users</div><h1>Manage users</h1><p>Create accounts, assign Free/Pro/Enterprise, suspend access, and promote admins.</p></div></div>';
    echo '<div class="panel"><h3>Create user</h3><form method="post" class="admin-inline-form">'.csrf_field().'<input type="hidden" name="action" value="admin_save_user"><input name="name" placeholder="Name" required><input name="email" type="email" placeholder="Email" required><input name="password" placeholder="Password" value="Angani@2026"><select name="tier_id">'; foreach($tiers as $t) echo '<option value="'.(int)$t['id'].'">'.e($t['name']).'</option>'; echo '</select><select name="role"><option>user</option><option>admin</option></select><select name="status"><option>active</option><option>suspended</option></select><button class="btn ink">Create</button></form></div>';
    echo '<form method="get" class="toolbar admin-toolbar"><input type="hidden" name="page" value="admin"><input type="hidden" name="tab" value="users"><label class="searchbox"><span>Search users</span><input name="q" value="'.e($q).'" placeholder="Name, email, role, status"></label><button class="btn ink">Search</button><a class="btn ghost" href="?page=admin&tab=users">Reset</a></form>';
    echo '<div class="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Tier</th><th>Role</th><th>Status</th><th>Last login</th><th>Action</th></tr></thead><tbody>'; foreach($users as $u){ echo '<tr><form style="display:contents" method="post">'.csrf_field().'<input type="hidden" name="action" value="admin_save_user"><input type="hidden" name="user_id" value="'.(int)$u['id'].'"><td><input name="name" value="'.e($u['name']).'"></td><td><input name="email" value="'.e($u['email']).'"></td><td><select name="tier_id">'; foreach($tiers as $t) echo '<option value="'.(int)$t['id'].'" '.((int)$t['id']===(int)$u['tier_id']?'selected':'').'>'.e($t['name']).'</option>'; echo '</select></td><td><select name="role"><option '.($u['role']==='user'?'selected':'').'>user</option><option '.($u['role']==='admin'?'selected':'').'>admin</option></select></td><td><select name="status"><option '.($u['status']==='active'?'selected':'').'>active</option><option '.($u['status']==='suspended'?'selected':'').'>suspended</option><option '.($u['status']==='deleted'?'selected':'').'>deleted</option></select></td><td>'.e($u['last_login_at'] ?? '—').'</td><td><button class="btn mini">Save</button></td></form></tr>'; } echo '</tbody></table></div>';
}
function render_admin_plans(): void {
    $tiers=rows('SELECT * FROM subscription_tiers ORDER BY display_order');
    echo '<div class="admin-head"><div><div class="eyebrow">Plans & Access</div><h1>Free / Pro / Enterprise</h1><p>Edit pricing, limits and visible benefits. Keep the public offer simple.</p></div></div><div class="pricing-grid admin-plan-grid">';
    foreach($tiers as $t){ echo '<article class="pricing-card"><form method="post" class="stack-form">'.csrf_field().'<input type="hidden" name="action" value="admin_save_tier"><input type="hidden" name="tier_id" value="'.(int)$t['id'].'"><label><span>Name</span><input name="name" value="'.e($t['name']).'"></label><label><span>Code</span><input name="code" value="'.e($t['code']).'"></label><label><span>Description</span><textarea name="description">'.e($t['description']).'</textarea></label><label><span>Monthly USD</span><input name="monthly_usd" value="'.e($t['monthly_usd']).'"></label><label><span>Annual USD</span><input name="annual_usd" value="'.e($t['annual_usd']).'"></label><label><span>Monthly exports</span><input name="export_limit_monthly" value="'.e($t['export_limit_monthly']).'"></label><label><span>API limit</span><input name="api_limit_monthly" value="'.e($t['api_limit_monthly']).'"></label><label><span>Order</span><input name="display_order" value="'.(int)$t['display_order'].'"></label><label><span>Active</span><select name="is_active"><option value="1" '.($t['is_active']?'selected':'').'>Yes</option><option value="0" '.(!$t['is_active']?'selected':'').'>No</option></select></label><button class="btn ink">Save plan</button></form><hr><h4>Benefits</h4><ul class="feature-list">'; foreach(rows('SELECT * FROM tier_features WHERE tier_id=? ORDER BY id',[(int)$t['id']]) as $f){ echo '<li>'.e($f['feature_label']).'<form method="post" class="inline-delete">'.csrf_field().'<input type="hidden" name="action" value="admin_delete_feature"><input type="hidden" name="feature_id" value="'.(int)$f['id'].'"><button class="btn mini danger">×</button></form></li>'; } echo '</ul><form method="post" class="inline-form">'.csrf_field().'<input type="hidden" name="action" value="admin_save_feature"><input type="hidden" name="tier_id" value="'.(int)$t['id'].'"><input name="feature_code" placeholder="feature_code" required><input name="feature_label" placeholder="Feature label" required><button class="btn mini">Add</button></form></article>'; }
    echo '</div>';
}
function render_admin_questions(): void {
    $qs=rows('SELECT qp.*, st.name tier_name FROM question_presets qp LEFT JOIN subscription_tiers st ON st.id=qp.required_tier_id ORDER BY qp.display_order, qp.id'); $tiers=tier_cards();
    echo '<div class="admin-head"><div><div class="eyebrow">Preset Questions</div><h1>User intelligence prompts</h1><p>These drive the logged-in dashboard. Use them to guide users toward valuable dataset answers.</p></div></div>';
    echo '<div class="panel"><h3>Add question</h3><form method="post" class="admin-form compact-form">'.csrf_field().'<input type="hidden" name="action" value="admin_save_question"><label><span>Code</span><input name="code" required></label><label><span>Title</span><input name="title" required></label><label><span>Category</span><input name="category" required></label><label><span>Answer key</span><input name="answer_key" required></label><label><span>Required tier</span><select name="required_tier_id"><option value="">Free</option>'; foreach($tiers as $t) echo '<option value="'.(int)$t['id'].'">'.e($t['name']).'</option>'; echo '</select></label><label><span>Order</span><input name="display_order" value="50"></label><label class="wide"><span>Question text</span><textarea name="question_text" required></textarea></label><label><span>Active</span><select name="is_active"><option value="1">Yes</option><option value="0">No</option></select></label><button class="btn ink">Add question</button></form></div>';
    echo '<div class="table-wrap"><table><thead><tr><th>Question</th><th>Category</th><th>Answer key</th><th>Tier</th><th>Order</th><th>Active</th><th>Save</th></tr></thead><tbody>'; foreach($qs as $q){ echo '<tr><form style="display:contents" method="post">'.csrf_field().'<input type="hidden" name="action" value="admin_save_question"><input type="hidden" name="id" value="'.(int)$q['id'].'"><td><input name="code" value="'.e($q['code']).'"><input name="title" value="'.e($q['title']).'"><textarea name="question_text">'.e($q['question_text']).'</textarea></td><td><input name="category" value="'.e($q['category']).'"></td><td><input name="answer_key" value="'.e($q['answer_key']).'"></td><td><select name="required_tier_id"><option value="">Free</option>'; foreach($tiers as $t) echo '<option value="'.(int)$t['id'].'" '.((int)$q['required_tier_id']===(int)$t['id']?'selected':'').'>'.e($t['name']).'</option>'; echo '</select></td><td><input name="display_order" value="'.(int)$q['display_order'].'"></td><td><select name="is_active"><option value="1" '.($q['is_active']?'selected':'').'>Yes</option><option value="0" '.(!$q['is_active']?'selected':'').'>No</option></select></td><td><button class="btn mini">Save</button></td></form></tr>'; } echo '</tbody></table></div>';
}
function render_admin_insights(): void {
    $cards=rows('SELECT ic.*, st.name tier_name FROM insight_cards ic LEFT JOIN subscription_tiers st ON st.id=ic.required_tier_id ORDER BY ic.display_order'); $tiers=tier_cards(); $queries=available_insight_queries();
    echo '<div class="admin-head"><div><div class="eyebrow">Homepage</div><h1>Manage rotating insights</h1><p>Use these cards to keep the public homepage fresh and convert visitors into signups.</p></div></div>';
    echo '<div class="panel"><h3>Add homepage insight</h3><form method="post" class="admin-form compact-form">'.csrf_field().'<input type="hidden" name="action" value="admin_save_insight"><label><span>Title</span><input name="title" required></label><label><span>Metric label</span><input name="metric_label"></label><label><span>Query</span><select name="query_key">'; foreach($queries as $k=>$label) echo '<option value="'.e($k).'">'.e($label).'</option>'; echo '</select></label><label><span>Chart</span><input name="chart_type" value="ranked_bar"></label><label><span>Required tier</span><select name="required_tier_id"><option value="">Public</option>'; foreach($tiers as $t) echo '<option value="'.(int)$t['id'].'">'.e($t['name']).'</option>'; echo '</select></label><label><span>Order</span><input name="display_order" value="50"></label><label><span>Active</span><select name="is_active"><option value="1">Yes</option><option value="0">No</option></select></label><label class="wide"><span>Description</span><textarea name="description"></textarea></label><button class="btn ink">Add insight</button></form></div>';
    echo '<div class="table-wrap"><table><thead><tr><th>Title</th><th>Metric</th><th>Query</th><th>Tier</th><th>Order</th><th>Active</th><th>Save</th></tr></thead><tbody>'; foreach($cards as $c){ echo '<tr><form style="display:contents" method="post">'.csrf_field().'<input type="hidden" name="action" value="admin_save_insight"><input type="hidden" name="id" value="'.(int)$c['id'].'"><td><input name="title" value="'.e($c['title']).'"><textarea name="description">'.e($c['description']).'</textarea></td><td><input name="metric_label" value="'.e($c['metric_label']).'"></td><td><select name="query_key">'; foreach($queries as $k=>$label) echo '<option value="'.e($k).'" '.($c['query_key']===$k?'selected':'').'>'.e($label).'</option>'; echo '</select><input name="chart_type" value="'.e($c['chart_type']).'"></td><td><select name="required_tier_id"><option value="">Public</option>'; foreach($tiers as $t) echo '<option value="'.(int)$t['id'].'" '.((int)$c['required_tier_id']===(int)$t['id']?'selected':'').'>'.e($t['name']).'</option>'; echo '</select></td><td><input name="display_order" value="'.(int)$c['display_order'].'"></td><td><select name="is_active"><option value="1" '.($c['is_active']?'selected':'').'>Yes</option><option value="0" '.(!$c['is_active']?'selected':'').'>No</option></select></td><td><button class="btn mini">Save</button></td></form></tr>'; } echo '</tbody></table></div>';
}
function render_admin_imports(): void {
    $module=getv('module','airlines'); $cfg=module_config($module);
    echo '<div class="admin-head"><div><div class="eyebrow">Data Operations</div><h1>Imports / Exports</h1><p>Import selected modules, export filtered records, or export a full CSV ZIP backup.</p></div><div class="hero-actions"><a class="btn primary" href="?page=export_all">Export whole database ZIP</a></div></div>';
    echo '<div class="panel-grid"><article class="panel"><h3>Import CSV to module</h3><form method="post" enctype="multipart/form-data" class="stack-form">'.csrf_field().'<input type="hidden" name="action" value="admin_import_csv"><label>Module<select name="module">'; foreach(modules() as $k=>$c) echo '<option value="'.e($k).'" '.($k===$module?'selected':'').'>'.e($c['label']).' — '.e($k).'</option>'; echo '</select></label><label>Import mode<select name="import_mode"><option value="append">Append new records</option><option value="truncate_append">Clear module then import</option></select></label><label>CSV file<input type="file" name="csv_file" accept=".csv" required></label><label>Batch notes<textarea name="notes" placeholder="Source, assumptions, or cleanup notes"></textarea></label><button class="btn ink">Import CSV</button></form><p class="muted">Headers are matched to editable field names. Failed rows are sent to Data Quality → Staging Records.</p></article>';
    echo '<article class="panel"><h3>Export selected module</h3><form method="get" class="stack-form"><input type="hidden" name="page" value="export"><label>Module<select name="module">'; foreach(modules() as $k=>$c) echo '<option value="'.e($k).'" '.($k===$module?'selected':'').'>'.e($c['label']).'</option>'; echo '</select></label><label>Search filter<input name="q" placeholder="Optional keyword"></label><label>Country filter'.country_select('country').'</label><button class="btn ink">Export filtered CSV</button></form><p class="muted">Admin exports respect filters and are logged in <strong>Export Logs</strong>.</p></article></div>';
    echo '<section class="panel"><h3>Phase 4 source importers</h3><p class="muted">For large source folders and country ZIP imports, run the CLI importer so long-running jobs are not interrupted by the browser.</p><div class="code-grid"><code>php scripts/importers/phase4_import.php --group=all</code><code>php scripts/importers/phase4_import.php --group=country --country=KE</code><code>php scripts/importers/phase4_import.php --group=aircraft</code><code>php scripts/importers/phase4_import.php --group=reference</code><code>php scripts/importers/phase4_import.php --group=commercial</code><code>php scripts/importers/phase4_import.php --group=infrastructure</code></div><p class="muted">Groups available: global, country, aircraft, reference, commercial, iata-iosa, gds, infrastructure. Use <code>--dry-run</code>, <code>--mode=replace</code>, <code>--limit=1000</code> or <code>--store-raw=1</code> when needed.</p></section>';
    echo '<section class="panel"><h3>Module export shortcuts</h3><div class="module-grid compact">'; foreach(module_groups() as $group=>$keys){ echo '<article class="module-group"><h3>'.e($group).'</h3><div>'; foreach($keys as $k){ $c=module_config($k); if($c) echo '<a class="module-chip" href="?page=export&module='.e($k).'"><b>'.module_icon_html($k).'</b><span>'.e($c['label']).'</span><em>'.nfmt(module_count($k)).'</em></a>'; } echo '</div></article>'; } echo '</div></section>';
    $logs=rows('SELECT * FROM import_batches ORDER BY started_at DESC LIMIT 20'); echo '<h3>Recent import batches</h3>'.render_table($logs,$logs?array_keys($logs[0]):[],null);
}
function render_admin_quality(): void {
    $staging=rows('SELECT * FROM staging_import_records ORDER BY created_at DESC LIMIT 100'); $batches=rows('SELECT * FROM import_batches ORDER BY started_at DESC LIMIT 50'); $exports=rows('SELECT el.*, u.email FROM export_logs el LEFT JOIN users u ON u.id=el.user_id ORDER BY el.created_at DESC LIMIT 50'); $empty=admin_empty_modules();
    $needs=admin_safe_count("SELECT COUNT(*) FROM staging_import_records WHERE status IN ('pending','needs_review','conflict')"); $failed=admin_safe_count("SELECT COUNT(*) FROM import_batches WHERE status IN ('failed','needs_review')");
    echo '<div class="admin-head"><div><div class="eyebrow">Data Quality</div><h1>Review queue</h1><p>Imports should not blindly become trusted aviation intelligence. Review failed rows, empty modules and export usage.</p></div></div><div class="admin-kpi-grid">'.admin_metric('Rows needing review',$needs,'Staging queue',$needs?'warning':'success').admin_metric('Import issues',$failed,'Failed/needs-review batches',$failed?'danger':'success').admin_metric('Empty modules',count($empty),'Awaiting data').admin_metric('Export logs',count($exports),'Recent exports').'</div>';
    echo '<section class="panel"><h3>Empty / awaiting-data modules</h3>'; if(!$empty) echo '<p class="muted">No empty configured modules.</p>'; else { echo '<div class="admin-empty-list">'; foreach($empty as $k=>$c) echo '<a href="?page=admin&tab=records&module='.e($k).'"><strong>'.e($c['label']).'</strong><small>'.e($k).'</small></a>'; echo '</div>'; } echo '</section>';
    echo '<section class="panel"><h3>Staging records</h3>'; if(!$staging) echo '<p class="muted">No staged import issues.</p>'; else { echo '<div class="table-wrap"><table><thead><tr><th>Module</th><th>Row</th><th>Status</th><th>Issue</th><th>Action</th></tr></thead><tbody>'; foreach($staging as $r){ echo '<tr><form style="display:contents" method="post">'.csrf_field().'<input type="hidden" name="action" value="admin_update_staging"><input type="hidden" name="staging_id" value="'.(int)$r['id'].'"><td>'.e($r['module_key']).'</td><td>'.e($r['source_row_number']).'</td><td><select name="status">'; foreach(['pending','needs_review','accepted','rejected','duplicate','conflict'] as $st) echo '<option '.($r['status']===$st?'selected':'').'>'.$st.'</option>'; echo '</select></td><td>'.display_value($r['issue_summary']).'</td><td><button class="btn mini">Update</button></td></form></tr>'; } echo '</tbody></table></div>'; } echo '</section>';
    echo '<section class="panel"><h3>Import batches</h3>'.render_table($batches,$batches?array_keys($batches[0]):[],null).'</section><section class="panel"><h3>Export logs</h3>'.render_table($exports,$exports?array_keys($exports[0]):[],null).'</section>';
}
function render_admin_tasks(): void { $tasks=rows('SELECT * FROM admin_tasks ORDER BY sort_order,id'); echo '<div class="admin-head"><div><div class="eyebrow">Readiness</div><h1>100% implementation checklist</h1><p>Track launch readiness from inside the admin console.</p></div></div><div class="table-wrap"><table><thead><tr><th>Category</th><th>Task</th><th>Status</th><th>Priority</th><th>Action</th></tr></thead><tbody>'; foreach($tasks as $t){ echo '<tr><form style="display:contents" method="post">'.csrf_field().'<input type="hidden" name="action" value="admin_update_task"><input type="hidden" name="task_id" value="'.(int)$t['id'].'"><td>'.e($t['category']).'</td><td><strong>'.e($t['task_title']).'</strong><p>'.e($t['description']).'</p></td><td><select name="status">'; foreach(['pending','in_progress','done','blocked'] as $st) echo '<option '.($t['status']===$st?'selected':'').'>'.$st.'</option>'; echo '</select></td><td>'.e($t['priority']).'</td><td><button class="btn mini">Update</button></td></form></tr>'; } echo '</tbody></table></div>'; }
function render_admin_pipeline(): void {
    $sub=getv('section','sources');
    echo '<div class="admin-head"><div><div class="eyebrow">Data Pipeline</div><h1>Pipeline manager</h1><p>Fetch, validate, review and publish data from external sources through the 4-stage pipeline.</p></div></div>';
    echo '<nav class="admin-module-nav">';
    foreach(['sources'=>'Sources','pending'=>'Pending Reviews','history'=>'Run History'] as $k=>$l){
        echo '<a class="'.($sub===$k?'active':'').'" href="?page=admin&tab=pipeline&section='.e($k).'">'.e($l).'</a>';
    }
    echo '</nav>';
    if($sub==='sources') render_pipeline_sources();
    elseif($sub==='pending') render_pipeline_pending();
    elseif($sub==='history') render_pipeline_history();
}
function render_pipeline_sources(): void {
    $sources=rows('SELECT * FROM pipeline_sources ORDER BY module_key,source_name');
    echo '<section class="panel"><h3>Add source</h3><form method="post" class="admin-form compact-form">'.csrf_field().'<input type="hidden" name="action" value="pipeline_add_source"><label><span>Source name</span><input name="source_name" required></label><label><span>Type</span><select name="source_type"><option value="api">API</option><option value="scraper">Web scraper</option><option value="csv_upload">CSV file</option><option value="url_csv">URL CSV</option></select></label><label><span>Module key</span><input name="module_key" placeholder="countries, caas, country_transport_stats" required></label><label><span>URL (for API / URL CSV)</span><input name="url" placeholder="https://..."></label><label><span>Notes</span><textarea name="notes" rows="2"></textarea></label><button class="btn ink">Add source</button></form></section>';
    echo '<section class="panel"><h3>Sources</h3><div class="table-wrap"><table><thead><tr><th>Name</th><th>Type</th><th>Module</th><th>Status</th><th>Last run</th><th>Actions</th></tr></thead><tbody>';
    foreach($sources as $s){
        $status='<span class="chip '.($s['is_active']?'ok glow-green':'gold').'">'.($s['is_active']?'Active':'Inactive').'</span>';
        $lastRun=$s['last_run_at'] ? e($s['last_run_at']).' <small>'.e($s['last_run_status'] ?? '').'</small>' : '—';
        echo '<tr><td><strong>'.e($s['source_name']).'</strong></td><td><span class="chip">'.e($s['source_type']).'</span></td><td>'.e($s['module_key']).'</td><td>'.$status.'</td><td>'.$lastRun.'</td><td>';
        echo '<form method="post" style="display:inline">'.csrf_field().'<input type="hidden" name="action" value="pipeline_run_source"><input type="hidden" name="source_id" value="'.(int)$s['id'].'"><button class="btn mini ink">Run now</button></form>';
        echo '</td></tr>';
    }
    echo '</tbody></table></div></section>';
}
function render_pipeline_pending(): void {
    $runs=rows("SELECT pr.*, ps.source_name FROM pipeline_runs pr LEFT JOIN pipeline_sources ps ON ps.id=pr.pipeline_source_id WHERE pr.status='pending_review' ORDER BY pr.started_at DESC LIMIT 20");
    if(!$runs){ echo '<section class="panel"><h3>Pending reviews</h3><p class="muted">No runs pending review.</p></section>'; return; }
    foreach($runs as $run){
        $records=rows('SELECT * FROM staging_records WHERE pipeline_run_id=? ORDER BY id',[(int)$run['id']]);
        echo '<section class="panel"><div class="topline"><h3>'.e($run['source_name'] ?: 'Source #'.$run['pipeline_source_id']).'</h3><span class="chip gold">'.e($run['module_key']).'</span><span class="chip">'.nfmt($run['records_fetched']).' fetched</span></div>';
        echo '<p>Run #'.(int)$run['id'].' · '.e($run['started_at']).'</p>';
        echo '<form method="post" style="display:inline">'.csrf_field().'<input type="hidden" name="action" value="pipeline_approve_run"><input type="hidden" name="run_id" value="'.(int)$run['id'].'"><button class="btn ink">Approve all</button></form> ';
        echo '<form method="post" style="display:inline">'.csrf_field().'<input type="hidden" name="action" value="pipeline_reject_run"><input type="hidden" name="run_id" value="'.(int)$run['id'].'"><button class="btn ghost">Reject all</button></form>';
        if($records){
            echo '<div class="table-wrap"><table><thead><tr><th>Action</th><th>Key</th><th>Status</th><th>Actions</th></tr></thead><tbody>';
            foreach($records as $r){
                $data=json_decode($r['row_data'],true);
                $key=$data['iso_alpha_2'] ?? $data['country_code'] ?? $data['name'] ?? '(no key)';
                echo '<tr><td><span class="chip '.($r['action']==='insert'?'ok':($r['action']==='update'?'gold':($r['action']==='delete'?'danger':''))).'">'.e($r['action']).'</span></td><td>'.e($key).'</td><td><span class="chip '.($r['status']==='approved'?'ok glow-green':($r['status']==='rejected'?'danger':'gold')).'">'.e($r['status']).'</span></td><td>';
                echo '<form method="post" style="display:inline">'.csrf_field().'<input type="hidden" name="action" value="pipeline_approve_staging"><input type="hidden" name="record_ids[]" value="'.(int)$r['id'].'"><button class="btn mini ink">Approve</button></form> ';
                echo '<form method="post" style="display:inline">'.csrf_field().'<input type="hidden" name="action" value="pipeline_reject_staging"><input type="hidden" name="record_ids[]" value="'.(int)$r['id'].'"><button class="btn mini ghost">Reject</button></form>';
                echo '</td></tr>';
            }
            echo '</tbody></table></div>';
        }
        echo '</section>';
    }
}
function render_pipeline_history(): void {
    $runs=rows('SELECT pr.*, ps.source_name FROM pipeline_runs pr LEFT JOIN pipeline_sources ps ON ps.id=pr.pipeline_source_id ORDER BY pr.started_at DESC LIMIT 100');
    echo '<section class="panel"><h3>Run history</h3><div class="table-wrap"><table><thead><tr><th>ID</th><th>Source</th><th>Module</th><th>Status</th><th>Fetched</th><th>Ins</th><th>Upd</th><th>Started</th><th>Finished</th></tr></thead><tbody>';
    foreach($runs as $r){
        $status=$r['status'];
        $cls=$status==='approved'?'ok glow-green':($status==='failed'?'danger':($status==='pending_review'?'gold':''));
        echo '<tr><td>#'.(int)$r['id'].'</td><td>'.e($r['source_name'] ?: '—').'</td><td>'.e($r['module_key']).'</td><td><span class="chip '.$cls.'">'.e($status).'</span></td><td>'.nfmt($r['records_fetched']).'</td><td>'.nfmt($r['records_insert']).'</td><td>'.nfmt($r['records_update']).'</td><td>'.e($r['started_at'] ?: '—').'</td><td>'.e($r['finished_at'] ?: '—').'</td></tr>';
    }
    echo '</tbody></table></div></section>';
}
?>
