SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS airport_frequencies;
CREATE TABLE airport_frequencies (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  airport_ident VARCHAR(20) NOT NULL,
  type VARCHAR(40) DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  frequency_mhz DECIMAL(12,4) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_freq_airport (airport_ident)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
