<?php
require_once __DIR__ . '/../includes/db.php';
$log=fn($m)=>printf("$m\n").file_put_contents(__DIR__.'/../logs/update_antigua.log','['.date('Y-m-d H:i:s')."] $m\n",FILE_APPEND);

$airlines=[
['name'=>'4 Island Air Services','iata'=>'FX','icao'=>'FIA','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1981','hubs'=>null,'parent'=>'Merged into LIAT (1974)','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>'4-island-air-services.png'],
['name'=>'Aerowings','iata'=>null,'icao'=>'AWG','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'2001','hubs'=>null,'parent'=>'Defunct','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Antigua Airways','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>1,'bucket'=>'defunct','founded'=>'2022','hubs'=>null,'parent'=>'Virtual airline; defunct 2023','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/Antigua-Airways','wiki'=>null,'web'=>null,'logo'=>'antigua-airways.png'],
['name'=>'Antigua Caribbean Airways','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'2007','hubs'=>null,'parent'=>'Short-lived; formed by Caribbean International Hotel','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Antigua International Airways','iata'=>'NQ','icao'=>'ABI','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1990','hubs'=>null,'parent'=>'Renamed Great Atlantic Airlines in 1991','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'CAIRGO','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1974','hubs'=>null,'parent'=>'Short-lived','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'CalvinAir Helicopters','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>4,'bucket'=>'active','founded'=>'2019','hubs'=>'V.C. Bird International Airport (ANU / TAPA)','parent'=>null,'legal'=>'CalvinAir Helicopters','trading'=>'CalvinAir Helicopters','src'=>'https://calvinair.com/','wiki'=>null,'web'=>'https://calvinair.com/','logo'=>null],
['name'=>'Carib Aviation','iata'=>'3Q','icao'=>'DEL','callsign'=>'RED TAIL','fleet'=>null,'bucket'=>'defunct','founded'=>'1972','hubs'=>'V.C. Bird International Airport (ANU / TAPA)','parent'=>null,'legal'=>'Carib Aviation','trading'=>'Carib Aviation','src'=>'https://www.planespotters.net/airline/Carib-Aviation','wiki'=>'https://en.wikipedia.org/wiki/Carib_Aviation','web'=>'http://www.carib-aviation.com','logo'=>null],
['name'=>'Caribbean Clipper Airways','iata'=>'HU','icao'=>'ABI','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1993','hubs'=>null,'parent'=>'Renamed Paradise Airways in 1994','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Caribbean Helicopters','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>10,'bucket'=>'defunct','founded'=>'1995','hubs'=>'V.C. Bird International Airport (ANU / TAPA)','parent'=>null,'legal'=>'Caribbean Helicopters Limited','trading'=>'Caribbean Helicopters','src'=>'https://en.wikipedia.org/wiki/Caribbean_Helicopters','wiki'=>'https://en.wikipedia.org/wiki/Caribbean_Helicopters','web'=>null,'logo'=>null],
['name'=>'Caribbean Star Airlines','iata'=>'8B','icao'=>'GFI','callsign'=>'CARIB STAR','fleet'=>null,'bucket'=>'defunct','founded'=>'2000','hubs'=>null,'parent'=>'Merged into LIAT (1974) in 2007','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>'caribbean-star-airlines.jpg'],
['name'=>'Caribbean Winds Airlines','iata'=>null,'icao'=>'WND','callsign'=>'WINDY','fleet'=>2,'bucket'=>'defunct','founded'=>'1995','hubs'=>null,'parent'=>'Defunct 1996','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/Caribbean-Winds-Airlines','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Caribjet','iata'=>null,'icao'=>'CBJ','callsign'=>'RIGEL','fleet'=>5,'bucket'=>'defunct','founded'=>'1992','hubs'=>null,'parent'=>'Renamed CBJ Cargo in 2000','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/Caribjet','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'CBJ Cargo','iata'=>null,'icao'=>'CBJ','callsign'=>'RIGEL','fleet'=>1,'bucket'=>'defunct','founded'=>'2000','hubs'=>null,'parent'=>'Defunct 2004','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/CBJ-Cargo','wiki'=>null,'web'=>null,'logo'=>'cbj-cargo.png'],
['name'=>'Eastern Caribbean Airways','iata'=>'HU','icao'=>'ABI','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1992','hubs'=>null,'parent'=>'Renamed Caribbean Clipper Airways in 1993','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Gold Aviation','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>1,'bucket'=>'defunct','founded'=>'1997','hubs'=>null,'parent'=>'Defunct 2001','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/Gold-Aviation','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Grand Atlantic Airways','iata'=>'NQ','icao'=>'ABI','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1990','hubs'=>null,'parent'=>'Defunct 1992','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Great Atlantic Airways','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>1,'bucket'=>'defunct','founded'=>'1991','hubs'=>null,'parent'=>'Defunct 1992','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/Great-Atlantic-Airways','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'LIAT','iata'=>'LI','icao'=>'LIA','callsign'=>'LIAT','fleet'=>null,'bucket'=>'defunct','founded'=>'1956','hubs'=>'V.C. Bird International Airport (ANU / TAPA)','parent'=>null,'legal'=>'LIAT (1974) Limited','trading'=>'LIAT (1974)','src'=>'https://www.planespotters.net/airline/LIAT','wiki'=>'https://en.wikipedia.org/wiki/LIAT_(1974)','web'=>null,'logo'=>'liat.jpg'],
['name'=>'LIAT - Leeward Islands Air Transport Services','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>7,'bucket'=>'defunct','founded'=>'1956','hubs'=>'V.C. Bird International Airport (ANU / TAPA)','parent'=>null,'legal'=>'Leeward Islands Air Transport Services Limited','trading'=>'LIAT (1956-1974)','src'=>'https://www.planespotters.net/airline/Leeward-Islands-Air-Transport-Services','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'LIAT20','iata'=>null,'icao'=>null,'callsign'=>null,'fleet'=>0,'bucket'=>'defunct','founded'=>'2020','hubs'=>null,'parent'=>'Predecessor of Liat Air','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/LIAT20','wiki'=>null,'web'=>null,'logo'=>'liat20.jpg'],
['name'=>'Liat Air','iata'=>'5L','icao'=>'GAO','callsign'=>'SOAR','fleet'=>4,'bucket'=>'active','founded'=>'2020','hubs'=>'V.C. Bird International Airport (ANU / TAPA)','parent'=>'Air Peace (70%), Government of Antigua and Barbuda (30%)','legal'=>null,'trading'=>'Liat Air (2020)','src'=>'https://www.planespotters.net/airline/Liat-Air','wiki'=>'https://en.wikipedia.org/wiki/Liat_Air','web'=>'https://flyliatair.com','logo'=>'liat-air.png'],
['name'=>'Paradise Airways','iata'=>'HU','icao'=>'ABI','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1994','hubs'=>null,'parent'=>'Renamed Prestige Airways in 1995','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Prestige Airways','iata'=>'HU','icao'=>'ABI','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1995','hubs'=>null,'parent'=>'Defunct','legal'=>null,'trading'=>null,'src'=>'https://en.wikipedia.org/wiki/List_of_airlines_of_Antigua_and_Barbuda','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Seagreen Air Transport','iata'=>'ES','icao'=>'ESA','callsign'=>'SEAGREEN','fleet'=>2,'bucket'=>'defunct','founded'=>'1972','hubs'=>null,'parent'=>'Defunct 1997','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/Seagreen-Air-Transport','wiki'=>null,'web'=>null,'logo'=>null],
['name'=>'Skyjet','iata'=>'XH','icao'=>'SKJ','callsign'=>null,'fleet'=>null,'bucket'=>'defunct','founded'=>'1992','hubs'=>null,'parent'=>'Defunct 2001','legal'=>null,'trading'=>null,'src'=>'https://www.planespotters.net/airline/Skyjet','wiki'=>null,'web'=>null,'logo'=>'skyjet.gif'],
];

$db=db();$u=0;$i=0;
$log("Starting Antigua & Barbuda (AG) update...");
foreach($airlines as $a){
    $lp=$a['logo']?'assets/airline_logos/'.$a['logo']:null;
    $ex=row("SELECT id FROM airlines WHERE name=? AND country_code='AG'",[$a['name']]);
    if($ex){
        $p=[$a['iata']??'', $a['icao']??'', $a['callsign']??'', $a['fleet'], $a['bucket']??'unknown', $a['founded']??'', $a['hubs']??'', $a['parent']??'', $a['legal']??'', $a['trading']??'', $a['src']??'', $a['wiki']??'', $a['web']??''];
        $s="UPDATE airlines SET iata_code=COALESCE(NULLIF(?,''),iata_code),icao_code=COALESCE(NULLIF(?,''),icao_code),callsign=COALESCE(NULLIF(?,''),callsign),fleet_size=COALESCE(?,fleet_size),status_bucket=?,founded=COALESCE(NULLIF(?,''),founded),hubs=COALESCE(NULLIF(?,''),hubs),parent_company=COALESCE(NULLIF(?,''),parent_company),legal_name=COALESCE(NULLIF(?,''),legal_name),trading_name=COALESCE(NULLIF(?,''),trading_name),source_url=COALESCE(NULLIF(?,''),source_url),wikipedia_url=COALESCE(NULLIF(?,''),wikipedia_url),website_url=COALESCE(NULLIF(?,''),website_url),country_code='AG',data_source=COALESCE(data_source,'planespotters_country_csv')".($lp?",logo_url=COALESCE(NULLIF(logo_url,''),?)":"")." WHERE id=?";
        if($lp)$p[]=$lp;$p[]=$ex['id'];
        exec_sql($s,$p);
        $log("UPDATED: {$a['name']} (id={$ex['id']})".($lp?" + logo":""));
        $u++;
    }else{
        $c=['name','country_code','data_source','status_bucket'];$v=[$a['name'],'AG','planespotters_country_csv',$a['bucket']??'unknown'];$q=['?','?','?','?'];
        $m=['iata_code'=>'iata','icao_code'=>'icao','callsign'=>'callsign','fleet_size'=>'fleet','founded'=>'founded','hubs'=>'hubs','parent_company'=>'parent','legal_name'=>'legal','trading_name'=>'trading','source_url'=>'src','wikipedia_url'=>'wiki','website_url'=>'web','logo_url'=>'logo'];
        foreach($m as $col=>$k){$vv=$col==='logo_url'?$lp:($a[$k]??null);if($vv!==null&&$vv!==''){$c[]=$col;$v[]=$vv;$q[]='?';}}
        exec_sql("INSERT INTO airlines (".implode(', ',$c).") VALUES (".implode(', ',$q).")",$v);
        $nid=$db->lastInsertId();$log("INSERTED: {$a['name']} (id=$nid)".($lp?" + logo":""));
        $i++;
    }
}
$log("Done! Updated: $u, Inserted: $i");
