<?php
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/functions.php';

$logFile = __DIR__ . '/../logs/update_algeria.log';
$logDir = dirname($logFile);
if (!is_dir($logDir)) mkdir($logDir, 0755, true);
function log_msg(string $msg): void {
    global $logFile;
    $line = '[' . date('Y-m-d H:i:s') . '] ' . $msg;
    echo $line . "\n";
    file_put_contents($logFile, $line . "\n", FILE_APPEND);
}

$airlines = [
    [
        'name' => 'Air Algérie',
        'iata_code' => 'AH',
        'icao_code' => 'DAH',
        'callsign' => 'AIR ALGERIE',
        'fleet_size' => 56,
        'status_bucket' => 'active',
        'status' => null,
        'founded' => '1947',
        'hubs' => 'Houari Boumedienne Airport, Algiers',
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Air Algérie SpA',
        'trading_name' => 'Air Algérie',
        'source_url' => 'https://www.planespotters.net/airline/Air-Algerie',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Air_Alg%C3%A9rie',
        'website_url' => 'https://www.airalgerie.dz/',
        'logo_file' => 'air-algerie.svg',
    ],
    [
        'name' => 'Air Express Algeria',
        'iata_code' => null,
        'icao_code' => null,
        'callsign' => 'Air Express',
        'fleet_size' => 15,
        'status_bucket' => 'active',
        'status' => null,
        'founded' => '2002',
        'hubs' => 'Oued Irara–Krim Belkacem Airport, Hassi Messaoud',
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Air Express Algeria',
        'trading_name' => 'Air Express Algeria',
        'source_url' => 'https://www.planespotters.net/airline/Air-Express-Algeria',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Air_Express_Algeria',
        'website_url' => 'http://www.airexpressdz.com',
        'logo_file' => null,
    ],
    [
        'name' => 'Star Aviation',
        'iata_code' => null,
        'icao_code' => 'DST',
        'callsign' => 'STAR AVIATION',
        'fleet_size' => 11,
        'status_bucket' => 'active',
        'status' => null,
        'founded' => '2001',
        'hubs' => 'Oued Irara–Krim Belkacem Airport, Hassi Messaoud',
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Star Aviation',
        'trading_name' => 'Star Aviation',
        'source_url' => 'https://www.planespotters.net/airline/Star-Aviation-Algeria',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Star_Aviation',
        'website_url' => null,
        'logo_file' => 'star-aviation-algeria.png',
    ],
    [
        'name' => 'Domestic Airlines',
        'iata_code' => 'SF',
        'icao_code' => 'DTH',
        'callsign' => 'TASSILI AIR',
        'fleet_size' => 15,
        'status_bucket' => 'active',
        'status' => null,
        'founded' => '2025',
        'hubs' => 'Houari Boumedienne Airport, Algiers',
        'alliance' => null,
        'parent_company' => 'Air Algérie',
        'legal_name' => 'Domestic Airlines',
        'trading_name' => 'Domestic Airlines',
        'source_url' => 'https://www.planespotters.net/airline/Domestic-Airlines',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Domestic_Airlines',
        'website_url' => 'https://www.tassiliairlines.dz/',
        'logo_file' => 'domestic-airlines.jpg',
    ],
    [
        'name' => 'Antinea Airlines',
        'iata_code' => 'HO',
        'icao_code' => 'DJA',
        'callsign' => 'ANTINEA',
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1999',
        'hubs' => 'Houari Boumedienne Airport, Algiers',
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Antinea Airlines',
        'trading_name' => 'Antinea Airlines',
        'source_url' => 'https://www.planespotters.net/airline/Antinea-Airlines',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Antinea_Airlines',
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'Ecoair International',
        'iata_code' => '9H',
        'icao_code' => 'DEI',
        'callsign' => null,
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1999',
        'hubs' => null,
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Ecoair International',
        'trading_name' => 'Ecoair International',
        'source_url' => 'https://www.planespotters.net/airline/Ecoair-International',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Ecoair_International',
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'Inter Air Services',
        'iata_code' => null,
        'icao_code' => null,
        'callsign' => null,
        'fleet_size' => 3,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1984',
        'hubs' => null,
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Inter Air Services',
        'trading_name' => 'Inter Air Services',
        'source_url' => 'https://www.planespotters.net/airline/Inter-Air-Services',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => null,
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'Khalifa Airways',
        'iata_code' => 'K6',
        'icao_code' => 'KZW',
        'callsign' => 'KHALIFA AIR',
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1999',
        'hubs' => 'Houari Boumedienne Airport, Algiers',
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Khalifa Airways',
        'trading_name' => 'Khalifa Airways',
        'source_url' => 'https://www.planespotters.net/airline/Khalifa-Airways',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Khalifa_Airways',
        'website_url' => null,
        'logo_file' => 'khalifa-airways.png',
    ],
    [
        'name' => 'Khalifa Airways Cargo',
        'iata_code' => null,
        'icao_code' => null,
        'callsign' => null,
        'fleet_size' => 1,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => null,
        'hubs' => null,
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Khalifa Airways Cargo',
        'trading_name' => 'Khalifa Airways Cargo',
        'source_url' => 'https://www.planespotters.net/airline/Khalifa-Airways-Cargo',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => null,
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'Rym Airlines',
        'iata_code' => null,
        'icao_code' => null,
        'callsign' => null,
        'fleet_size' => 2,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '2003',
        'hubs' => 'Oran Es Senia Airport, Oran',
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Rym Airlines',
        'trading_name' => 'Rym Airlines',
        'source_url' => 'https://www.planespotters.net/airline/Rym-Airlines',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Rym_Airlines',
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'Sahara Airlines',
        'iata_code' => '6S',
        'icao_code' => 'SHD',
        'callsign' => null,
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1998',
        'hubs' => null,
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Sahara Airlines',
        'trading_name' => 'Sahara Airlines',
        'source_url' => 'https://www.planespotters.net/airline/Sahara-Airlines-Algeria',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Sahara_Airlines_(Algeria)',
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'Tassili Airlines',
        'iata_code' => 'SF',
        'icao_code' => 'DTH',
        'callsign' => 'TASSILI AIR',
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1998',
        'hubs' => 'Houari Boumedienne Airport, Algiers',
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Tassili Airlines',
        'trading_name' => 'Tassili Airlines',
        'source_url' => 'https://www.planespotters.net/airline/Tassili-Airlines',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Tassili_Airlines',
        'website_url' => null,
        'logo_file' => 'tassili-airlines.png',
    ],
    [
        'name' => 'Aéro-Africaine',
        'iata_code' => null,
        'icao_code' => null,
        'callsign' => null,
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1945',
        'hubs' => null,
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Aéro-Africaine',
        'trading_name' => 'Aéro-Africaine',
        'source_url' => 'https://www.planespotters.net/airline/Aero-Africaine',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/A%C3%A9ro-Africaine',
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'Afric Air',
        'iata_code' => null,
        'icao_code' => null,
        'callsign' => null,
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1964',
        'hubs' => null,
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Afric Air',
        'trading_name' => 'Afric Air',
        'source_url' => 'https://www.planespotters.net/airline/Afric-Air',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => null,
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'Compagnie Air Transport',
        'iata_code' => null,
        'icao_code' => null,
        'callsign' => null,
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1946',
        'hubs' => null,
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'Compagnie Air Transport',
        'trading_name' => 'Compagnie Air Transport',
        'source_url' => 'https://www.planespotters.net/airline/Compagnie-Air-Transport',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => 'https://en.wikipedia.org/wiki/Compagnie_Air_Transport',
        'website_url' => null,
        'logo_file' => null,
    ],
    [
        'name' => 'North African Airways',
        'iata_code' => null,
        'icao_code' => null,
        'callsign' => null,
        'fleet_size' => null,
        'status_bucket' => 'defunct',
        'status' => null,
        'founded' => '1980',
        'hubs' => null,
        'alliance' => null,
        'parent_company' => null,
        'legal_name' => 'North African Airways',
        'trading_name' => 'North African Airways',
        'source_url' => 'https://www.planespotters.net/airline/North-African-Airways',
        'destinations_count' => null,
        'logo_url' => null,
        'wikipedia_url' => null,
        'website_url' => null,
        'logo_file' => null,
    ],
];

log_msg("Starting Algerian airlines update...");

$db = db();
$updated = 0;
$inserted = 0;

foreach ($airlines as $a) {
    $name = $a['name'];
    $cc = 'DZ';

    $existing = row("SELECT id, logo_url FROM airlines WHERE name = ? AND country_code = ?", [$name, $cc]);

    $logoPath = $a['logo_file'] ? 'assets/airline_logos/' . $a['logo_file'] : null;

    if ($existing) {
        $sql = "UPDATE airlines SET
            iata_code = COALESCE(NULLIF(?, ''), iata_code),
            icao_code = COALESCE(NULLIF(?, ''), icao_code),
            callsign = COALESCE(NULLIF(?, ''), callsign),
            fleet_size = COALESCE(?, fleet_size),
            status_bucket = ?,
            status = COALESCE(NULLIF(?, ''), status),
            founded = COALESCE(NULLIF(?, ''), founded),
            hubs = COALESCE(NULLIF(?, ''), hubs),
            alliance = COALESCE(NULLIF(?, ''), alliance),
            parent_company = COALESCE(NULLIF(?, ''), parent_company),
            legal_name = COALESCE(NULLIF(?, ''), legal_name),
            trading_name = COALESCE(NULLIF(?, ''), trading_name),
            source_url = COALESCE(NULLIF(?, ''), source_url),
            wikipedia_url = COALESCE(NULLIF(?, ''), wikipedia_url),
            website_url = COALESCE(NULLIF(?, ''), website_url),
            country_code = ?,
            data_source = COALESCE(data_source, 'planespotters_country_csv')
            " . ($logoPath ? ", logo_url = COALESCE(NULLIF(logo_url, ''), ?)" : "") . "
            WHERE id = ?";

        $params = [
            $a['iata_code'] ?? '',
            $a['icao_code'] ?? '',
            $a['callsign'] ?? '',
            $a['fleet_size'],
            $a['status_bucket'] ?? 'unknown',
            $a['status'] ?? '',
            $a['founded'] ?? '',
            $a['hubs'] ?? '',
            $a['alliance'] ?? '',
            $a['parent_company'] ?? '',
            $a['legal_name'] ?? '',
            $a['trading_name'] ?? '',
            $a['source_url'] ?? '',
            $a['wikipedia_url'] ?? '',
            $a['website_url'] ?? '',
            $cc,
        ];
        if ($logoPath) $params[] = $logoPath;
        $params[] = $existing['id'];

        exec_sql($sql, $params);
        log_msg("UPDATED: {$name} (id={$existing['id']})" . ($logoPath ? " + logo" : ""));
        $updated++;
    } else {
        $cols = ['name', 'country_code', 'data_source', 'status_bucket'];
        $vals = [$name, $cc, 'planespotters_country_csv', $a['status_bucket'] ?? 'unknown'];
        $phs = ['?', '?', '?', '?'];

        $fieldMap = [
            'iata_code', 'icao_code', 'callsign', 'fleet_size',
            'status', 'founded', 'hubs', 'alliance', 'parent_company',
            'legal_name', 'trading_name', 'source_url', 'logo_url',
            'wikipedia_url', 'website_url',
        ];
        foreach ($fieldMap as $f) {
            $v = ($f === 'logo_url') ? $logoPath : ($a[$f] ?? null);
            if ($v !== null && $v !== '') {
                $cols[] = $f;
                $vals[] = $v;
                $phs[] = '?';
            }
        }

        $sql = "INSERT INTO airlines (" . implode(', ', $cols) . ") VALUES (" . implode(', ', $phs) . ")";
        exec_sql($sql, $vals);
        $newId = $db->lastInsertId();
        log_msg("INSERTED: {$name} (id={$newId})" . ($logoPath ? " + logo" : ""));
        $inserted++;
    }
}

log_msg("Done! Updated: {$updated}, Inserted: {$inserted}");
