<?php
function e($v):string{return htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');}
function fmt($v):string{if($v===null||$v===''||$v==0)return '—';return number_format((float)$v);} function nfmt($v):string{return number_format((float)$v);} function active_page(string $p,string $t):string{return $p===$t?'active':'';}
function status_chip(?string $b):string{$b=$b?:'unknown';$class=$b==='active'?'ok':($b==='defunct'?'danger':'gold');return '<span class="chip '.$class.'">'.e(ucfirst($b)).'</span>';}
function initials(string $name):string{preg_match_all('/\b[A-Za-z]/',$name,$m);$letters=implode('',array_slice($m[0]??[],0,2));return strtoupper($letters?:substr($name,0,2));}
function hue(string $v):int{return (int)(crc32($v)%360);} function getv(string $k,$d=''){return trim((string)($_GET[$k]??$d));} function page_num():int{return max(1,(int)($_GET['p']??1));}
function query_string(array $override=[]):string{$q=array_merge($_GET,$override);foreach($q as $k=>$v){if($v===''||$v===null)unset($q[$k]);}return http_build_query($q);} function paginate(int $total,int $per):string{if($total<=$per)return ''; $p=page_num();$pages=(int)ceil($total/$per);$prev=max(1,$p-1);$next=min($pages,$p+1);return '<div class="pager"><a class="btn ghost" href="?'.e(query_string(['p'=>$prev])).'">← Previous</a><span>Page '.e($p).' of '.e($pages).'</span><a class="btn ghost" href="?'.e(query_string(['p'=>$next])).'">Next →</a></div>';}
function option_tags(array $items,string $sel,string $label='All'):string{$html='<option value="all">'.e($label).'</option>';foreach($items as $it){$value=is_array($it)?($it['value']??''):$it;$lab=is_array($it)?($it['label']??$value):$value;$html.='<option value="'.e($value).'" '.($sel===(string)$value?'selected':'').'>'.e($lab).'</option>'; } return $html;}
function country_name(?string $code):string{if(!$code)return 'Unknown';$r=row('SELECT name FROM countries WHERE code=?',[$code]);return $r['name']??$code;} function country_options():array{return rows("SELECT code AS value, CONCAT(name, ' (', code, ')') AS label FROM countries WHERE code <> 'GLOBAL' ORDER BY name");}
function metric_card(string $num,string $label,string $note=''):string{return '<div class="stat-card"><strong>'.e($num).'</strong><span>'.e($label).'</span>'.($note?'<small>'.e($note).'</small>':'').'</div>';}
function get_stats():array{return ['airlines'=>(int)scalar('SELECT COUNT(*) FROM airlines'),'active_airlines'=>(int)scalar("SELECT COUNT(*) FROM airlines WHERE status_bucket='active'"),'defunct_airlines'=>(int)scalar("SELECT COUNT(*) FROM airlines WHERE status_bucket='defunct'"),'airports'=>(int)scalar('SELECT COUNT(*) FROM airports'),'aircraft'=>(int)scalar('SELECT COUNT(*) FROM aircraft_registrations'),'aircraft_types'=>(int)scalar('SELECT COUNT(*) FROM aircraft_types'),'regulatory'=>(int)scalar('SELECT COUNT(*) FROM regulatory_records'),'countries'=>(int)scalar("SELECT COUNT(*) FROM countries WHERE code <> 'GLOBAL'"),'dataset_files'=>(int)scalar('SELECT COUNT(*) FROM dataset_files'),'populated_files'=>(int)scalar('SELECT COUNT(*) FROM dataset_files WHERE is_populated=1'),'raw_records'=>(int)scalar('SELECT COUNT(*) FROM dataset_records')];}
function airline_summary(array $a):string{$bits=[];$bits[]=$a['name'].' is recorded as '.(($a['status_bucket']??'')==='active'?'an active':((($a['status_bucket']??'')==='defunct')?'a defunct/inactive':'an')).' airline record'; if(($a['country_code']??'')&&$a['country_code']!=='GLOBAL')$bits[]='associated with '.country_name($a['country_code']);$codes=[];if(!empty($a['iata_code']))$codes[]='IATA '.$a['iata_code'];if(!empty($a['icao_code']))$codes[]='ICAO '.$a['icao_code'];if($codes)$bits[]='with '.implode(' and ',$codes);if(!empty($a['fleet_size']))$bits[]='and a recorded fleet size of '.number_format((int)$a['fleet_size']);return implode(' ',$bits).'.';}
