<?php
function module_groups(): array {
    return [
        'Core' => ['countries','airlines','airports','aircraft','aircraft_types','lessors','routes','country_time_series','country_air_transport_stats'],
        'Airline Intelligence' => ['airline_digital','frequent_flyer','airline_fleet_list','airline_fleet_summary','airline_hubs','airline_it','airline_people','airline_stats'],
        'Airport & Infrastructure' => ['airport_frequencies','airport_runways','airport_terminals','airport_services','airport_hubs','airport_financial','airport_ground_handling','airport_ground_transport','airport_it','airport_people','navaids','navaid_technical','navaid_operational','navaid_connectivity','navaid_references','notam_sources','notams','notam_classification','notam_content','notam_schedule','notam_connectivity','notam_references'],
        'Aircraft Intelligence' => ['aircraft_manufacturers','aircraft_profile','aircraft_assets','aircraft_cabin_payload','aircraft_engine_data','aircraft_economic_data','aircraft_environmental','aircraft_manufacturer_support','aircraft_performance','aircraft_runways','aircraft_technical_specs','aircraft_models','aircraft_model_history','aircraft_model_capacity','aircraft_model_specs','aircraft_model_production','aircraft_model_sources'],
        'Regulatory & Standards' => ['regulatory','regulatory_authorities','regulatory_economic','regulatory_operational','regulatory_environmental','regulatory_references','regulatory_safety','regulatory_licensing','iata_membership','iosa_registration','airline_iata','airline_iosa'],
        'Commercial' => ['commercial_fares','commercial_inventory','commercial_rules','commercial_taxes','commercial_yield','country_fare_policies','gds'],
        'Reference' => ['ref_country_codes','ref_service_types','ref_meal_codes','ref_booking_classes','ref_terminal_codes','ref_reject_reasons','ref_phonetic'],
        'Data Quality' => ['dataset_files','source_records','change_log','import_batches','staging_records','export_logs']
    ];
}

function modules(): array {
    return [
        'countries'=>['label'=>'Countries','table'=>'countries','icon'=>'🌍','tier'=>'free','title'=>'name_common','subtitle'=>'iso_alpha_2','search'=>['iso_alpha_2','iso_alpha_3','name_common','name_official','continent','un_region','description'],'list'=>['iso_alpha_2','name_common','continent','un_region'],'detail'=>['iso_alpha_2','iso_alpha_3','name_common','name_official','continent','un_region','flag','description'],'fields'=>['iso_alpha_2','iso_alpha_3','name_common','name_official','continent','un_region','flag','description'],'card'=>'country'],
        'country_air_transport_stats'=>['label'=>'Country Air Transport Stats','table'=>'country_air_transport_stats','icon'=>'Σ','tier'=>'free','title'=>'iso_alpha_2','subtitle'=>'international_airports','search'=>['iso_alpha_2','international_airports','domestic_airports','airlines','airlines_with_international','foreign_airline_operations'],'list'=>['iso_alpha_2','international_airports','domestic_airports','airlines','airlines_with_international','foreign_airline_operations'],'detail'=>['iso_alpha_2','international_airports','domestic_airports','airlines','airlines_with_international','foreign_airline_operations','updated_at'],'fields'=>['iso_alpha_2','international_airports','domestic_airports','airlines','airlines_with_international','foreign_airline_operations'],'card'=>'default'],
        'country_time_series'=>['label'=>'Country Time Series','table'=>'country_time_series','icon'=>'📈','tier'=>'free','title'=>'iso_alpha_2','subtitle'=>'year','search'=>['iso_alpha_2','year','gdp_usd','population','currency_code','currency_name','official_languages','capital'],'list'=>['iso_alpha_2','year','gdp_usd','population','currency_code','capital'],'detail'=>['iso_alpha_2','year','gdp_usd','population','area_sq_km','currency_code','currency_name','official_languages','capital','international_traffic_passengers','domestic_traffic_passengers','international_cargo_tonnes','domestic_cargo_tonnes','updated_at'],'fields'=>['iso_alpha_2','year','gdp_usd','population','area_sq_km','currency_code','currency_name','official_languages','capital','international_traffic_passengers','domestic_traffic_passengers','international_cargo_tonnes','domestic_cargo_tonnes'],'card'=>'default'],
        'airlines'=>['label'=>'Airlines','table'=>'airlines','icon'=>'✈','tier'=>'free','title'=>'name','subtitle'=>'icao_code','search'=>['name','iata_code','icao_code','callsign','country_code'],'list'=>['name','iata_code','icao_code','callsign','country_code','fleet_size'],'detail'=>['name','iata_code','icao_code','callsign','country_code','fleet_size','status_bucket','source_url','last_modified'],'fields'=>['name','iata_code','icao_code','callsign','country_code','fleet_size','status_bucket','source_url'],'card'=>'airline'],
        'airports'=>['label'=>'Airports','table'=>'airports','icon'=>'🛫','tier'=>'free','title'=>'name','subtitle'=>'ident','search'=>['name','iata_code','gps_code','ident','iso_country','municipality','keywords'],'list'=>['name','iata_code','gps_code','iso_country','municipality','type','elevation_ft'],'detail'=>['name','iata_code','gps_code','ident','type','iso_country','municipality','continent','latitude_deg','longitude_deg','elevation_ft','scheduled_service','home_link','wikipedia_link','keywords','updated_at'],'fields'=>['name','iata_code','gps_code','ident','type','iso_country','municipality','continent','latitude_deg','longitude_deg','elevation_ft','scheduled_service','home_link','wikipedia_link','keywords'],'card'=>'airport'],
        'aircraft'=>['label'=>'Aircraft Registry','table'=>'aircraft_registrations','icon'=>'🛩','tier'=>'pro','title'=>'registration','subtitle'=>'aircraft_type','search'=>['registration','aircraft_type','icao_code','operator_name','operator_icao','country_code'],'list'=>['registration','aircraft_type','type_code','operator_name','operator_icao','country_code','age'],'detail'=>['registration','icao_code','aircraft_type','type_code','construction_number','adshex','age','operator_name','operator_icao','country_code','record_status','date_modified'],'fields'=>['registration','icao_code','aircraft_type','type_code','construction_number','adshex','age','operator_name','operator_icao','country_code','record_status'],'card'=>'aircraft'],
        'aircraft_types'=>['label'=>'Aircraft Types','table'=>'aircraft_types','icon'=>'▰','tier'=>'free','title'=>'model','subtitle'=>'icao_code','search'=>['manufacturer','model','iata_code','icao_code','type','engine_type'],'list'=>['manufacturer','model','iata_code','icao_code','type','engine_type','wtc'],'detail'=>['manufacturer','model','iata_code','icao_code','type','description','engine_type','engine_count','wtc','updated_at'],'fields'=>['manufacturer','model','iata_code','icao_code','type','description','engine_type','engine_count','wtc'],'card'=>'aircraft_type'],
        'lessors'=>['label'=>'Lessors','table'=>'lessors','icon'=>'🏦','tier'=>'pro','title'=>'name','subtitle'=>'hq_location','search'=>['name','lessor_code','hq_location','status','contact_info'],'list'=>['name','lessor_code','hq_location','fleet_count','status'],'detail'=>['lessor_code','name','hq_location','headquarters_country_code','fleet_count','contact_info','status','notes','updated_at'],'fields'=>['lessor_code','name','hq_location','headquarters_country_code','fleet_count','contact_info','status','notes'],'card'=>'lessor'],
        'routes'=>['label'=>'Routes & Schedules','table'=>'airline_route_services','icon'=>'↔','tier'=>'pro','title'=>'flight_number_prefix','subtitle'=>'status','search'=>['flight_number_prefix','service_type','status','notes'],'list'=>['flight_number_prefix','service_type','status','start_date','end_date'],'detail'=>['route_market_id','airline_id','flight_number_prefix','service_type','status','start_date','end_date','booking_url','notes'],'fields'=>['route_market_id','airline_id','flight_number_prefix','service_type','status','start_date','end_date','booking_url','notes']],

        'airline_digital'=>['label'=>'Airline Digital Properties','table'=>'airline_digital_properties','icon'=>'@','tier'=>'pro','title'=>'airline_name','subtitle'=>'platform','search'=>['airline_name','iata_code','icao_code','category','platform','url_or_handle'],'list'=>['airline_name','iata_code','icao_code','category','platform','url_or_handle','is_primary'],'detail'=>['airline_name','iata_code','icao_code','country_code','category','platform','description','url_or_handle','is_primary','last_modified'],'fields'=>['country_code','iata_code','icao_code','airline_name','category','platform','description','url_or_handle','is_primary']],
        'frequent_flyer'=>['label'=>'Frequent Flyer Programmes','table'=>'frequent_flyer_programs','icon'=>'★','tier'=>'free','title'=>'program_name','subtitle'=>'airline_name','search'=>['airline_name','airline_code','program_name','points_unit','notes'],'list'=>['airline_name','airline_code','program_name','points_unit'],'detail'=>['airline_name','airline_code','iata_code','icao_code','program_name','tier_level','points_unit','website_url','notes','last_modified'],'fields'=>['country_code','airline_name','airline_code','iata_code','icao_code','program_name','tier_level','points_unit','website_url','notes']],
        'airline_fleet_list'=>['label'=>'Airline Fleet List','table'=>'airline_fleet_list','icon'=>'▣','tier'=>'pro','title'=>'registration','subtitle'=>'operator_airline','search'=>['registration','msn','aircraft_model','aircraft_subtype','operator_airline','current_status'],'list'=>['registration','aircraft_model','aircraft_subtype','operator_airline','current_status','delivery_date'],'detail'=>['registration','msn','aircraft_model','aircraft_subtype','delivery_date','operator_airline','current_status','country_code','last_modified'],'fields'=>['country_code','registration','msn','aircraft_model','aircraft_subtype','delivery_date','operator_airline','current_status']],
        'airline_fleet_summary'=>['label'=>'Airline Fleet Summary','table'=>'airline_fleet_summary','icon'=>'▤','tier'=>'pro','title'=>'aircraft_type','subtitle'=>'icao_code','search'=>['iata_code','icao_code','aircraft_type','engine_type'],'list'=>['iata_code','icao_code','aircraft_type','aircraft_count','average_age','engine_type'],'detail'=>['country_code','iata_code','icao_code','aircraft_type','aircraft_count','configuration_lopa','average_age','engine_type','last_modified'],'fields'=>['country_code','iata_code','icao_code','aircraft_type','aircraft_count','configuration_lopa','average_age','engine_type']],
        'airline_hubs'=>['label'=>'Airline Hubs & Bases','table'=>'airline_hubs','icon'=>'⌖','tier'=>'pro','title'=>'airport_code','subtitle'=>'hub_type','search'=>['iata_code','icao_code','airport_code','hub_type','region_served','description'],'list'=>['iata_code','icao_code','airport_code','hub_type','region_served'],'detail'=>['country_code','iata_code','icao_code','airport_code','hub_type','region_served','description','last_modified'],'fields'=>['country_code','iata_code','icao_code','airport_code','hub_type','region_served','description']],
        'airline_it'=>['label'=>'Airline IT Infrastructure','table'=>'airline_it_infrastructure','icon'=>'IT','tier'=>'pro','title'=>'system_name','subtitle'=>'provider','search'=>['iata_code','icao_code','system_category','system_name','provider','description'],'list'=>['iata_code','icao_code','system_category','system_name','provider'],'detail'=>['country_code','iata_code','icao_code','system_category','system_name','provider','description','last_modified'],'fields'=>['country_code','iata_code','icao_code','system_category','system_name','provider','description']],
        'airline_people'=>['label'=>'Airline Key Personnel','table'=>'airline_key_personnel','icon'=>'👤','tier'=>'pro','title'=>'person_name','subtitle'=>'title','search'=>['person_name','title','category','iata_code','icao_code','email'],'list'=>['person_name','title','category','iata_code','icao_code'],'detail'=>['country_code','iata_code','icao_code','person_name','title','category','email','phone','last_modified'],'fields'=>['country_code','iata_code','icao_code','person_name','title','category','email','phone']],
        'airline_stats'=>['label'=>'Airline Operational Stats','table'=>'airline_operational_stats','icon'=>'Σ','tier'=>'pro','title'=>'icao_code','subtitle'=>'stat_year','search'=>['iata_code','icao_code','stat_year'],'list'=>['iata_code','icao_code','stat_year','pax_count','cargo_volume','revenue','staff_count'],'detail'=>['country_code','iata_code','icao_code','stat_year','pax_count','cargo_volume','revenue','ebit','staff_count','last_modified'],'fields'=>['country_code','iata_code','icao_code','stat_year','pax_count','cargo_volume','revenue','ebit','staff_count']],

        'airport_frequencies'=>['label'=>'Airport Frequencies','table'=>'airport_frequencies','icon'=>'📡','tier'=>'free','title'=>'type','subtitle'=>'airport_ident','search'=>['airport_ident','type','description'],'list'=>['airport_ident','type','frequency_mhz','description'],'detail'=>['airport_ident','type','description','frequency_mhz','updated_at'],'fields'=>['airport_ident','type','description','frequency_mhz']],
        'airport_runways'=>['label'=>'Airport Runways','table'=>'airport_runways','icon'=>'━','tier'=>'pro','title'=>'runway_ident','subtitle'=>'icao_code','search'=>['icao_code','iata_code','runway_ident','surface','lighting'],'list'=>['icao_code','iata_code','runway_ident','length_ft','width_ft','surface','lighting'],'detail'=>['country_code','icao_code','iata_code','runway_ident','length_ft','width_ft','surface','lighting','ils_frequency','last_modified'],'fields'=>['country_code','icao_code','iata_code','runway_ident','length_ft','width_ft','surface','lighting','ils_frequency']],
        'airport_terminals'=>['label'=>'Airport Terminals','table'=>'airport_terminals','icon'=>'T','tier'=>'pro','title'=>'terminal_name','subtitle'=>'icao_code','search'=>['icao_code','iata_code','terminal_type','terminal_name','facilities'],'list'=>['icao_code','iata_code','terminal_type','terminal_name','capacity','gates_count'],'detail'=>['country_code','icao_code','iata_code','terminal_type','terminal_name','capacity','facilities','gates_count','last_modified'],'fields'=>['country_code','icao_code','iata_code','terminal_type','terminal_name','capacity','facilities','gates_count']],
        'airport_services'=>['label'=>'Airport Services','table'=>'airport_services','icon'=>'S','tier'=>'pro','title'=>'service_category','subtitle'=>'provider','search'=>['icao_code','iata_code','service_category','provider','description'],'list'=>['icao_code','iata_code','service_category','provider'],'detail'=>['country_code','icao_code','iata_code','service_category','provider','description','last_modified'],'fields'=>['country_code','icao_code','iata_code','service_category','provider','description']],
        'airport_hubs'=>['label'=>'Airport Hub Airlines','table'=>'airport_hubs_and_airlines','icon'=>'H','tier'=>'pro','title'=>'airline_name','subtitle'=>'relation','search'=>['icao_code','iata_code','airline_name','relation','destinations_served'],'list'=>['icao_code','iata_code','airline_name','relation'],'detail'=>['country_code','icao_code','iata_code','airline_name','relation','destinations_served','last_modified'],'fields'=>['country_code','icao_code','iata_code','airline_name','relation','destinations_served']],
        'airport_financial'=>['label'=>'Airport Financial Performance','table'=>'airport_financial_performance','icon'=>'FIN','tier'=>'pro','title'=>'icao_code','subtitle'=>'stat_year','search'=>['country_code','icao_code','iata_code','stat_year','ownership_structure'],'list'=>['country_code','icao_code','iata_code','stat_year','revenue','profit_loss','investment'],'detail'=>['country_code','icao_code','iata_code','stat_year','revenue','profit_loss','investment','staff_count','ownership_structure','last_modified'],'fields'=>['country_code','icao_code','iata_code','stat_year','revenue','profit_loss','investment','staff_count','ownership_structure']],
        'airport_ground_handling'=>['label'=>'Airport Ground Handling','table'=>'airport_ground_handling','icon'=>'GND','tier'=>'pro','title'=>'company','subtitle'=>'icao_code','search'=>['country_code','icao_code','iata_code','company','categories','contract_info'],'list'=>['country_code','icao_code','iata_code','company','categories'],'detail'=>['country_code','icao_code','iata_code','company','categories','contract_info','last_modified'],'fields'=>['country_code','icao_code','iata_code','company','categories','contract_info']],
        'airport_ground_transport'=>['label'=>'Airport Ground Transport','table'=>'airport_ground_transport','icon'=>'BUS','tier'=>'pro','title'=>'transport_mode','subtitle'=>'provider','search'=>['country_code','icao_code','iata_code','transport_mode','provider','link_description'],'list'=>['country_code','icao_code','iata_code','transport_mode','provider'],'detail'=>['country_code','icao_code','iata_code','transport_mode','provider','link_description','last_modified'],'fields'=>['country_code','icao_code','iata_code','transport_mode','provider','link_description']],
        'airport_it'=>['label'=>'Airport IT Infrastructure','table'=>'airport_it_infrastructure','icon'=>'AIT','tier'=>'pro','title'=>'system_name','subtitle'=>'provider','search'=>['country_code','icao_code','iata_code','category','system_name','provider','innovation_notes'],'list'=>['country_code','icao_code','iata_code','category','system_name','provider'],'detail'=>['country_code','icao_code','iata_code','category','system_name','provider','innovation_notes','last_modified'],'fields'=>['country_code','icao_code','iata_code','category','system_name','provider','innovation_notes']],
        'airport_people'=>['label'=>'Airport Key Personnel','table'=>'airport_key_personnel','icon'=>'PEO','tier'=>'pro','title'=>'person_name','subtitle'=>'title','search'=>['country_code','icao_code','iata_code','person_name','title','category','contact'],'list'=>['country_code','icao_code','iata_code','person_name','title','category'],'detail'=>['country_code','icao_code','iata_code','person_name','title','category','contact','last_modified'],'fields'=>['country_code','icao_code','iata_code','person_name','title','category','contact']],
        'navaids'=>['label'=>'Navaids','table'=>'navaids','icon'=>'◉','tier'=>'free','title'=>'name','subtitle'=>'ident','search'=>['ident','name','type','iso_country'],'list'=>['ident','name','type','iso_country','frequency_khz','elevation_ft'],'detail'=>['ident','name','type','iso_country','latitude_deg','longitude_deg','elevation_ft','frequency_khz','updated_at'],'fields'=>['ident','name','type','iso_country','latitude_deg','longitude_deg','elevation_ft','frequency_khz']],
        'navaid_technical'=>['label'=>'Navaid Technical','table'=>'navaid_technical','icon'=>'MHz','tier'=>'pro','title'=>'frequency','subtitle'=>'country_code','search'=>['source_navaid_id','frequency','channel_number','morse_code','signal_type','equipment_model'],'list'=>['country_code','frequency','channel_number','signal_type','equipment_model'],'detail'=>['source_navaid_id','country_code','frequency','channel_number','morse_code','signal_type','power_output','equipment_model','redundancy_systems','last_modified'],'fields'=>['source_navaid_id','country_code','frequency','channel_number','morse_code','signal_type','power_output','equipment_model','redundancy_systems']],
        'navaid_operational'=>['label'=>'Navaid Operational','table'=>'navaid_operational','icon'=>'OPS','tier'=>'pro','title'=>'service_volume','subtitle'=>'country_code','search'=>['source_navaid_id','service_volume','status','maintenance_authority'],'list'=>['country_code','service_volume','range_nm','status','maintenance_authority'],'detail'=>['source_navaid_id','country_code','service_volume','range_nm','mag_variation','status','maintenance_authority','date_commissioned','last_inspection','last_modified'],'fields'=>['source_navaid_id','country_code','service_volume','range_nm','mag_variation','status','maintenance_authority','date_commissioned','last_inspection']],
        'navaid_connectivity'=>['label'=>'Navaid Connectivity','table'=>'navaid_connectivity','icon'=>'NAVC','tier'=>'pro','title'=>'associated_airports','subtitle'=>'country_code','search'=>['country_code','source_navaid_id','associated_airports','associated_airways','system_integration'],'list'=>['country_code','associated_airports','associated_airways','system_integration'],'detail'=>['country_code','source_navaid_id','associated_airports','associated_airways','system_integration','interoperability_notes','last_modified'],'fields'=>['country_code','source_navaid_id','associated_airports','associated_airways','system_integration','interoperability_notes']],
        'navaid_references'=>['label'=>'Navaid References','table'=>'navaid_references','icon'=>'NAVR','tier'=>'pro','title'=>'country_code','subtitle'=>'additional_notes','search'=>['country_code','source_navaid_id','additional_notes','data_sources'],'list'=>['country_code','additional_notes','data_sources'],'detail'=>['country_code','source_navaid_id','additional_notes','data_sources','last_modified'],'fields'=>['country_code','source_navaid_id','additional_notes','data_sources']],
        'notam_sources'=>['label'=>'NOTAM Sources','table'=>'notam_sources','icon'=>'!','tier'=>'free','title'=>'official_source_name','subtitle'=>'iso_country','search'=>['iso_country','country_name','official_source_name','notam_portal_url','icao_nof_code'],'list'=>['iso_country','country_name','official_source_name','icao_nof_code'],'detail'=>['iso_country','country_name','official_source_name','notam_portal_url','icao_nof_code','notes','last_verified_at','last_modified'],'fields'=>['iso_country','country_name','official_source_name','notam_portal_url','icao_nof_code','notes']],
        'notams'=>['label'=>'NOTAM Archive','table'=>'notams','icon'=>'NOTAM','tier'=>'pro','title'=>'series_number','subtitle'=>'notam_type','search'=>['series_number','notam_type','issuing_authority','summary','raw_text','country_code'],'list'=>['series_number','notam_type','issuing_authority','country_code','status'],'detail'=>['source_notam_id','country_code','series_number','notam_type','issuing_authority','summary','raw_text','start_utc','end_utc','status','last_modified'],'fields'=>['source_notam_id','country_code','series_number','notam_type','issuing_authority','summary','raw_text','start_utc','end_utc','status']],

        'regulatory'=>['label'=>'Regulatory Records','table'=>'regulatory_records','icon'=>'⚖','tier'=>'pro','title'=>'name','subtitle'=>'country_code','search'=>['type','country_code','name','regulator_name','airline_iata','airline_icao','aoc_number','authority','website'],'list'=>['type','country_code','name','regulator_name','aoc_number','status_bucket'],'detail'=>['type','country_code','name','regulator_name','airline_iata','airline_icao','aoc_number','authority','city','country','email','phone','website','status','status_bucket'],'fields'=>['type','country_code','name','regulator_name','airline_iata','airline_icao','aoc_number','authority','city','country','email','phone','website','status','status_bucket']],
        'regulatory_authorities'=>['label'=>'Civil Aviation Authorities','table'=>'regulatory_authorities','icon'=>'CAA','tier'=>'free','title'=>'name','subtitle'=>'country_code','search'=>['name','abbreviation','country_code','jurisdiction','key_officials','website'],'list'=>['country_code','name','abbreviation','hq_location','website'],'detail'=>['country_code','name','abbreviation','jurisdiction','hq_location','founding_year','governance_structure','key_officials','website','official_register_link','unofficial_register_link','aoc_holders_list','aircraft_registry','contacts','icao_caa_link','wikipedia_url','verification_notes','icao_member_since','last_modified'],'fields'=>['country_code','name','abbreviation','jurisdiction','hq_location','founding_year','governance_structure','key_officials','website','official_register_link','unofficial_register_link','aoc_holders_list','aircraft_registry','contacts','icao_caa_link','wikipedia_url','verification_notes','icao_member_since']],
        'regulatory_economic'=>['label'=>'Economic Licensing','table'=>'regulatory_economic_licensing','icon'=>'LAW','tier'=>'pro','title'=>'country_code','subtitle'=>'foreign_ownership_limit','search'=>['country_code','license_types','foreign_ownership_limit','cabotage_rights','air_service_agreements','market_access_policies'],'list'=>['country_code','license_types','foreign_ownership_limit','cabotage_rights'],'detail'=>['country_code','license_types','foreign_ownership_limit','cabotage_rights','air_service_agreements','market_access_policies','last_modified'],'fields'=>['country_code','license_types','foreign_ownership_limit','cabotage_rights','air_service_agreements','market_access_policies']],
        'regulatory_operational'=>['label'=>'Operational Certification','table'=>'regulatory_operational_certification','icon'=>'AOC','tier'=>'pro','title'=>'country_code','subtitle'=>'aoc_registry','search'=>['country_code','aoc_registry','authorized_aircraft','operational_limits','amo_mro_approvals','ato_approvals'],'list'=>['country_code','aoc_registry','authorized_aircraft','operational_limits'],'detail'=>['country_code','aoc_registry','authorized_aircraft','operational_limits','amo_mro_approvals','ato_approvals','renewal_dates','last_modified'],'fields'=>['country_code','aoc_registry','authorized_aircraft','operational_limits','amo_mro_approvals','ato_approvals','renewal_dates']],
        'regulatory_licensing'=>['label'=>'Licensing Categories','table'=>'regulatory_licensing_categories','icon'=>'LIC','tier'=>'free','title'=>'name','subtitle'=>'category','search'=>['iso_country','category','name','requirements','description'],'list'=>['iso_country','category','name','validity','cost'],'detail'=>['iso_country','category','name','validity','cost','requirements','description','last_modified'],'fields'=>['iso_country','category','name','validity','cost','requirements','description']],
        'iata_membership'=>['label'=>'IATA Membership Requirements','table'=>'iata_membership_requirements','icon'=>'IATA','tier'=>'free','title'=>'detail','subtitle'=>'section','search'=>['section','detail','description'],'list'=>['section','detail','description'],'detail'=>['section','detail','description','sort_order','last_modified'],'fields'=>['section','detail','description','sort_order']],
        'iosa_registration'=>['label'=>'IOSA Registration Steps','table'=>'iosa_registration_steps','icon'=>'IOSA','tier'=>'free','title'=>'action','subtitle'=>'step','search'=>['step','action','description'],'list'=>['step','action','description'],'detail'=>['step','action','description','sort_order','last_modified'],'fields'=>['step','action','description','sort_order']],
        'airline_iata'=>['label'=>'Airline IATA Membership','table'=>'airline_iata_membership','icon'=>'IATA+','tier'=>'pro','title'=>'airline_name','subtitle'=>'membership_status','search'=>['airline_name','iata_code','icao_code','membership_status','membership_type'],'list'=>['airline_name','iata_code','icao_code','membership_status','membership_type'],'detail'=>['airline_name','iata_code','icao_code','membership_status','membership_type','joined_date','ended_date','source_url','last_verified_at','last_modified'],'fields'=>['airline_name','iata_code','icao_code','membership_status','membership_type','joined_date','ended_date','source_url']],
        'airline_iosa'=>['label'=>'Airline IOSA Registration','table'=>'airline_iosa_registration','icon'=>'IOSA+','tier'=>'pro','title'=>'airline_name','subtitle'=>'iosa_status','search'=>['airline_name','iata_code','icao_code','iosa_status','registration_number'],'list'=>['airline_name','iata_code','icao_code','iosa_status','valid_until'],'detail'=>['airline_name','iata_code','icao_code','iosa_status','registration_number','valid_from','valid_until','source_url','last_verified_at','last_modified'],'fields'=>['airline_name','iata_code','icao_code','iosa_status','registration_number','valid_from','valid_until','source_url']],

        'commercial_fares'=>['label'=>'Fares','table'=>'commercial_fares','icon'=>'$','tier'=>'pro','title'=>'fare_id','subtitle'=>'airline_code','search'=>['fare_id','airline_code','origin_iata','destination_iata','date_seasonality'],'list'=>['fare_id','airline_code','origin_iata','destination_iata','base_fare','total_fare','currency_code'],'detail'=>['fare_id','airline_code','flight_number_schedule_id','origin_iata','destination_iata','date_seasonality','base_fare','total_fare','currency_code','snapshot_date','last_modified'],'fields'=>['fare_id','airline_code','flight_number_schedule_id','origin_iata','destination_iata','date_seasonality','base_fare','total_fare','currency_code','snapshot_date']],
        'commercial_inventory'=>['label'=>'Fare Inventory','table'=>'commercial_fare_inventory','icon'=>'RBD','tier'=>'pro','title'=>'fare_id','subtitle'=>'booking_class_code_rbd','search'=>['fare_id','cabin_class','fare_family','booking_class_code_rbd','baggage_allowance'],'list'=>['fare_id','cabin_class','fare_family','booking_class_code_rbd','baggage_allowance'],'detail'=>['fare_id','cabin_class','fare_family','booking_class_code_rbd','baggage_allowance','ancillary_services','last_modified'],'fields'=>['fare_id','cabin_class','fare_family','booking_class_code_rbd','baggage_allowance','ancillary_services']],
        'commercial_rules'=>['label'=>'Fare Rules','table'=>'commercial_fare_rules','icon'=>'RULE','tier'=>'pro','title'=>'fare_id','subtitle'=>'refundability','search'=>['fare_id','refundability','change_fees','min_stay','max_stay','blackout_dates_restrictions'],'list'=>['fare_id','refundability','change_fees','advance_purchase_requirement_days','min_stay','max_stay'],'detail'=>['fare_id','refundability','change_fees','advance_purchase_requirement_days','min_stay','max_stay','blackout_dates_restrictions','last_modified'],'fields'=>['fare_id','refundability','change_fees','advance_purchase_requirement_days','min_stay','max_stay','blackout_dates_restrictions']],
        'commercial_taxes'=>['label'=>'Taxes & Fees','table'=>'commercial_taxes_fees','icon'=>'TAX','tier'=>'pro','title'=>'fare_id','subtitle'=>'total_taxes_fees','search'=>['fare_id'],'list'=>['fare_id','surcharge_yq_yr','airport_taxes','government_taxes','other_fees','total_taxes_fees'],'detail'=>['fare_id','surcharge_yq_yr','airport_taxes','government_taxes','other_fees','total_taxes_fees','last_modified'],'fields'=>['fare_id','surcharge_yq_yr','airport_taxes','government_taxes','other_fees','total_taxes_fees']],
        'commercial_yield'=>['label'=>'Yield Analysis','table'=>'commercial_yield_analysis','icon'=>'YLD','tier'=>'pro','title'=>'fare_id','subtitle'=>'yield_per_km_cpk','search'=>['fare_id','load_factor_impact','competitor_benchmark'],'list'=>['fare_id','yield_per_km_cpk','revenue_per_passenger','price_gap_vs_competitor'],'detail'=>['fare_id','yield_per_km_cpk','revenue_per_passenger','load_factor_impact','competitor_benchmark','price_gap_vs_competitor','last_modified'],'fields'=>['fare_id','yield_per_km_cpk','revenue_per_passenger','load_factor_impact','competitor_benchmark','price_gap_vs_competitor']],
        'country_fare_policies'=>['label'=>'Country Fare Policies','table'=>'country_fare_policies','icon'=>'POL','tier'=>'pro','title'=>'country_code','subtitle'=>'carrier_code','search'=>['country_code','carrier_code','tax_policy','currency_standard'],'list'=>['country_code','carrier_code','avg_domestic_yield','avg_intl_yield','currency_standard'],'detail'=>['country_code','carrier_code','avg_domestic_yield','avg_intl_yield','tax_policy','currency_standard','last_modified'],'fields'=>['country_code','carrier_code','avg_domestic_yield','avg_intl_yield','tax_policy','currency_standard']],
        'gds'=>['label'=>'GDS Systems','table'=>'gds_systems','icon'=>'GDS','tier'=>'free','title'=>'company','subtitle'=>'gds_code','search'=>['gds_code','company','region','notes'],'list'=>['gds_code','company','region','notes'],'detail'=>['gds_code','company','region','notes','last_modified'],'fields'=>['gds_code','company','region','notes']],

        'aircraft_profile'=>['label'=>'Aircraft Type Profile Data','table'=>'aircraft_type_profile_data','icon'=>'INFO','tier'=>'pro','title'=>'aircraft_name','subtitle'=>'aircraft_role','search'=>['aircraft_name','country_of_origin','aircraft_role','powerplants','performance','history'],'list'=>['aircraft_name','country_of_origin','aircraft_role'],'detail'=>['aircraft_name','country_of_origin','aircraft_role','powerplants','performance','weights','dimensions','capacity','production','history','source_url','last_modified'],'fields'=>['aircraft_name','country_of_origin','aircraft_role','powerplants','performance','weights','dimensions','capacity','production','history','source_url']],
        'aircraft_assets'=>['label'=>'Aircraft Type Assets','table'=>'aircraft_type_assets','icon'=>'IMG','tier'=>'pro','title'=>'icao_code','subtitle'=>'iata_code','search'=>['iata_code','icao_code','primary_livery_url','lopa_template_url'],'list'=>['iata_code','icao_code','primary_livery_url','lopa_template_url'],'detail'=>['iata_code','icao_code','primary_livery_url','lopa_template_url','cockpit_reference_url','last_modified'],'fields'=>['iata_code','icao_code','primary_livery_url','lopa_template_url','cockpit_reference_url']],
        'aircraft_manufacturers'=>['label'=>'Aircraft Manufacturers','table'=>'aircraft_manufacturers','icon'=>'🏭','tier'=>'free','title'=>'name','subtitle'=>'industry','search'=>['name','legal_name','industry','headquarters','products','key_people'],'list'=>['name','industry','headquarters','founded_year','is_active'],'detail'=>['name','legal_name','organisation_type','industry','headquarters','founded_year','ceased_year','key_people','products','employee_count','website','logo_url','is_active','status','fate'],'fields'=>['name','legal_name','organisation_type','industry','headquarters','founded_year','ceased_year','key_people','products','employee_count','website','logo_url','is_active','status','fate','parent_manufacturer_id','predecessor_manufacturer_id','successor_manufacturer_id']],
        'aircraft_cabin_payload'=>['label'=>'Aircraft Cabin & Payload','table'=>'aircraft_type_cabin_payload','icon'=>'CAB','tier'=>'pro','title'=>'icao_code','subtitle'=>'max_capacity','search'=>['iata_code','icao_code'],'list'=>['iata_code','icao_code','typical_c_seats','typical_y_seats','max_capacity','cargo_volume_m3','max_payload_kg'],'detail'=>['iata_code','icao_code','typical_c_seats','typical_y_seats','max_capacity','cargo_volume_m3','max_payload_kg','last_modified'],'fields'=>['iata_code','icao_code','typical_c_seats','typical_y_seats','max_capacity','cargo_volume_m3','max_payload_kg']],
        'aircraft_engine_data'=>['label'=>'Aircraft Engine Data','table'=>'aircraft_type_engine_data','icon'=>'ENG','tier'=>'pro','title'=>'icao_code','subtitle'=>'engine_type','search'=>['iata_code','icao_code','engine_variants','engine_type','saf_compatible'],'list'=>['iata_code','icao_code','engine_type','engine_count','thrust_per_engine_kn','saf_compatible'],'detail'=>['iata_code','icao_code','engine_variants','engine_type','engine_count','thrust_per_engine_kn','fuel_burn_rate','saf_compatible','last_modified'],'fields'=>['iata_code','icao_code','engine_variants','engine_type','engine_count','thrust_per_engine_kn','fuel_burn_rate','saf_compatible']],
        'aircraft_economic_data'=>['label'=>'Aircraft Economic Data','table'=>'aircraft_type_economic_data','icon'=>'ECO','tier'=>'pro','title'=>'icao_code','subtitle'=>'list_price_usd','search'=>['iata_code','icao_code','residual_value_trend'],'list'=>['iata_code','icao_code','list_price_usd','op_cost_per_hour','lease_rate_monthly','residual_value_trend'],'detail'=>['iata_code','icao_code','list_price_usd','op_cost_per_hour','lease_rate_monthly','residual_value_trend','last_modified'],'fields'=>['iata_code','icao_code','list_price_usd','op_cost_per_hour','lease_rate_monthly','residual_value_trend']],
        'aircraft_environmental'=>['label'=>'Aircraft Environmental Data','table'=>'aircraft_type_environmental_data','icon'=>'ENV','tier'=>'pro','title'=>'icao_code','subtitle'=>'noise_chapter','search'=>['iata_code','icao_code','carbon_intensity','noise_chapter','fuel_type'],'list'=>['iata_code','icao_code','carbon_intensity','noise_chapter','fuel_type'],'detail'=>['iata_code','icao_code','carbon_intensity','noise_chapter','fuel_type','last_modified'],'fields'=>['iata_code','icao_code','carbon_intensity','noise_chapter','fuel_type']],
        'aircraft_manufacturer_support'=>['label'=>'Manufacturer Support','table'=>'aircraft_type_manufacturer_support','icon'=>'OEM','tier'=>'pro','title'=>'icao_code','subtitle'=>'production_start','search'=>['iata_code','icao_code','mro_availability'],'list'=>['iata_code','icao_code','production_start','production_end','total_built','mro_availability'],'detail'=>['iata_code','icao_code','production_start','production_end','total_built','mro_availability','last_modified'],'fields'=>['iata_code','icao_code','production_start','production_end','total_built','mro_availability']],
        'aircraft_performance'=>['label'=>'Aircraft Operational Performance','table'=>'aircraft_type_operational_performance','icon'=>'PERF','tier'=>'pro','title'=>'icao_code','subtitle'=>'max_range_nm','search'=>['iata_code','icao_code','max_speed','climb_rate'],'list'=>['iata_code','icao_code','max_range_nm','service_ceiling_ft','cruise_speed_mach','max_speed'],'detail'=>['iata_code','icao_code','max_range_nm','service_ceiling_ft','v1','vr','v2','vref','cruise_speed_mach','max_speed','climb_rate','last_modified'],'fields'=>['iata_code','icao_code','max_range_nm','service_ceiling_ft','v1','vr','v2','vref','cruise_speed_mach','max_speed','climb_rate']],
        'aircraft_runways'=>['label'=>'Aircraft Runway Requirements','table'=>'aircraft_type_runway_requirements','icon'=>'RWY','tier'=>'pro','title'=>'icao_code','subtitle'=>'min_takeoff_length_ft','search'=>['iata_code','icao_code','surface_compatibility'],'list'=>['iata_code','icao_code','min_takeoff_length_ft','min_landing_length_ft','surface_compatibility'],'detail'=>['iata_code','icao_code','min_takeoff_length_ft','min_landing_length_ft','surface_compatibility','last_modified'],'fields'=>['iata_code','icao_code','min_takeoff_length_ft','min_landing_length_ft','surface_compatibility']],
        'aircraft_technical_specs'=>['label'=>'Aircraft Technical Specs','table'=>'aircraft_type_technical_specs','icon'=>'SPEC','tier'=>'pro','title'=>'icao_code','subtitle'=>'mtow_kg','search'=>['iata_code','icao_code'],'list'=>['iata_code','icao_code','mtow_kg','mzfw_kg','empty_weight_kg','wingspan_m','length_m','height_m'],'detail'=>['iata_code','icao_code','mtow_kg','mzfw_kg','empty_weight_kg','wingspan_m','length_m','height_m','last_modified'],'fields'=>['iata_code','icao_code','mtow_kg','mzfw_kg','empty_weight_kg','wingspan_m','length_m','height_m']],
        'aircraft_models'=>['label'=>'Aircraft Models Encyclopedia','table'=>'aircraft_models','icon'=>'BOOK','tier'=>'free','title'=>'model_name','subtitle'=>'model_id','search'=>['model_id','model_name','origin','role','iata_type_ref'],'list'=>['model_id','model_name','origin','role','iata_type_ref'],'detail'=>['model_id','model_name','origin','role','iata_type_ref','last_modified'],'fields'=>['model_id','model_name','origin','role','iata_type_ref']],
        'aircraft_model_history'=>['label'=>'Aircraft Model History','table'=>'aircraft_model_history','icon'=>'HIST','tier'=>'pro','title'=>'model_id','subtitle'=>'status','search'=>['model_id','development_story','milestones','status'],'list'=>['model_id','status','development_story'],'detail'=>['model_id','development_story','milestones','status','last_modified'],'fields'=>['model_id','development_story','milestones','status']],
        'aircraft_model_capacity'=>['label'=>'Aircraft Model Capacity','table'=>'aircraft_model_capacity','icon'=>'CAP','tier'=>'pro','title'=>'model_id','subtitle'=>'seating_config','search'=>['model_id','seating_config','cargo_vol','configurations'],'list'=>['model_id','seating_config','cargo_vol'],'detail'=>['model_id','seating_config','cargo_vol','configurations','last_modified'],'fields'=>['model_id','seating_config','cargo_vol','configurations']],
        'aircraft_model_specs'=>['label'=>'Aircraft Model Specs','table'=>'aircraft_model_specs','icon'=>'MSP','tier'=>'pro','title'=>'model_id','subtitle'=>'powerplant_desc','search'=>['model_id','powerplant_desc','weights','dimensions','performance'],'list'=>['model_id','powerplant_desc','weights'],'detail'=>['model_id','powerplant_desc','weights','dimensions','performance','last_modified'],'fields'=>['model_id','powerplant_desc','weights','dimensions','performance']],
        'aircraft_model_production'=>['label'=>'Aircraft Model Production','table'=>'aircraft_model_production','icon'=>'PROD','tier'=>'pro','title'=>'model_id','subtitle'=>'production_years','search'=>['model_id','units_built','production_years','price_usd'],'list'=>['model_id','units_built','production_years','price_usd'],'detail'=>['model_id','units_built','production_years','price_usd','last_modified'],'fields'=>['model_id','units_built','production_years','price_usd']],
        'aircraft_model_sources'=>['label'=>'Aircraft Model Sources','table'=>'aircraft_model_sources','icon'=>'SRC','tier'=>'pro','title'=>'bibliography','subtitle'=>'model_id','search'=>['model_id','source_url','bibliography'],'list'=>['model_id','bibliography'],'detail'=>['model_id','source_url','bibliography','last_modified'],'fields'=>['model_id','source_url','bibliography']],

        'notam_classification'=>['label'=>'NOTAM Classification','table'=>'notam_classification','icon'=>'NCL','tier'=>'pro','title'=>'source_notam_id','subtitle'=>'subject_code','search'=>['country_code','source_notam_id','subject_code','modifier_code','traffic_code','purpose_code','scope','issuing_nof'],'list'=>['country_code','source_notam_id','subject_code','purpose_code','scope'],'detail'=>['country_code','source_notam_id','subject_code','modifier_code','traffic_code','purpose_code','scope','issuing_nof','last_modified'],'fields'=>['country_code','source_notam_id','subject_code','modifier_code','traffic_code','purpose_code','scope','issuing_nof']],
        'notam_content'=>['label'=>'NOTAM Content','table'=>'notam_content','icon'=>'NCT','tier'=>'pro','title'=>'source_notam_id','subtitle'=>'restriction_type','search'=>['country_code','source_notam_id','raw_text','cleaned_text','flight_level_limits','affected_area_radius','restriction_type'],'list'=>['country_code','source_notam_id','restriction_type','flight_level_limits'],'detail'=>['country_code','source_notam_id','raw_text','cleaned_text','flight_level_limits','affected_area_radius','restriction_type','last_modified'],'fields'=>['country_code','source_notam_id','raw_text','cleaned_text','flight_level_limits','affected_area_radius','restriction_type']],
        'notam_schedule'=>['label'=>'NOTAM Schedule','table'=>'notam_schedule','icon'=>'NSC','tier'=>'pro','title'=>'source_notam_id','subtitle'=>'start_utc','search'=>['country_code','source_notam_id','start_utc','end_utc','schedule_notes','perm_temp_flag','date_issued'],'list'=>['country_code','source_notam_id','start_utc','end_utc','perm_temp_flag'],'detail'=>['country_code','source_notam_id','start_utc','end_utc','schedule_notes','perm_temp_flag','date_issued','last_modified'],'fields'=>['country_code','source_notam_id','start_utc','end_utc','schedule_notes','perm_temp_flag','date_issued']],
        'notam_connectivity'=>['label'=>'NOTAM Connectivity','table'=>'notam_connectivity','icon'=>'NCN','tier'=>'pro','title'=>'source_notam_id','subtitle'=>'associated_airports','search'=>['country_code','source_notam_id','associated_airports','associated_navaids','associated_airways','affected_procedures','interoperability_notes'],'list'=>['country_code','source_notam_id','associated_airports','associated_navaids'],'detail'=>['country_code','source_notam_id','associated_airports','associated_navaids','associated_airways','affected_procedures','interoperability_notes','last_modified'],'fields'=>['country_code','source_notam_id','associated_airports','associated_navaids','associated_airways','affected_procedures','interoperability_notes']],
        'notam_references'=>['label'=>'NOTAM References','table'=>'notam_references','icon'=>'NRF','tier'=>'pro','title'=>'source_notam_id','subtitle'=>'country_code','search'=>['country_code','source_notam_id','additional_notes','data_sources','replacement_reference'],'list'=>['country_code','source_notam_id','additional_notes'],'detail'=>['country_code','source_notam_id','additional_notes','data_sources','replacement_reference','last_modified'],'fields'=>['country_code','source_notam_id','additional_notes','data_sources','replacement_reference']],
        'ref_country_codes'=>['label'=>'Country Codes','table'=>'ref_country_codes','icon'=>'ISO','tier'=>'free','title'=>'country_name','subtitle'=>'alpha_2','search'=>['country_name','alpha_2','alpha_3','numeric_code','aircraft_prefix'],'list'=>['country_name','alpha_2','alpha_3','numeric_code','aircraft_prefix'],'detail'=>['country_name','alpha_2','alpha_3','numeric_code','aircraft_prefix','last_modified'],'fields'=>['country_name','alpha_2','alpha_3','numeric_code','aircraft_prefix']],
        'ref_service_types'=>['label'=>'Service Type Codes','table'=>'ref_service_types','icon'=>'SVC','tier'=>'free','title'=>'service_type_code','subtitle'=>'service_type','search'=>['service_type_code','application','type_of_operation','service_type','description'],'list'=>['service_type_code','application','type_of_operation','service_type'],'detail'=>['service_type_code','application','type_of_operation','service_type','description','last_modified'],'fields'=>['service_type_code','application','type_of_operation','service_type','description']],
        'ref_meal_codes'=>['label'=>'Meal Service Codes','table'=>'ref_meal_service_codes','icon'=>'MEAL','tier'=>'free','title'=>'code','subtitle'=>'meaning','search'=>['code','meaning'],'list'=>['code','meaning'],'detail'=>['code','meaning','last_modified'],'fields'=>['code','meaning']],
        'ref_booking_classes'=>['label'=>'Booking Classes','table'=>'ref_booking_classes','icon'=>'RBD','tier'=>'free','title'=>'class_code','subtitle'=>'category','search'=>['category','class_code','description','class_type'],'list'=>['category','class_code','class_type','rank_order','description'],'detail'=>['category','class_code','description','class_type','rank_order','last_modified'],'fields'=>['category','class_code','description','class_type','rank_order']],
        'ref_terminal_codes'=>['label'=>'Passenger Terminal Codes','table'=>'ref_passenger_terminal_codes','icon'=>'TERM','tier'=>'free','title'=>'code','subtitle'=>'meaning','search'=>['code','meaning'],'list'=>['code','meaning'],'detail'=>['code','meaning','last_modified'],'fields'=>['code','meaning']],
        'ref_reject_reasons'=>['label'=>'Reject Reasons','table'=>'ref_reject_reasons','icon'=>'ASM','tier'=>'free','title'=>'reject_reason','subtitle'=>'id','search'=>['reject_reason'],'list'=>['reject_reason'],'detail'=>['reject_reason','last_modified'],'fields'=>['reject_reason']],
        'ref_phonetic'=>['label'=>'Phonetic Alphabet','table'=>'ref_phonetic_alphabet','icon'=>'ABC','tier'=>'free','title'=>'character_code','subtitle'=>'phonetic','search'=>['character_code','phonetic'],'list'=>['character_code','phonetic'],'detail'=>['character_code','phonetic','last_modified'],'fields'=>['character_code','phonetic']],
        'ref_timezones'=>['label'=>'Timezones','table'=>'ref_timezones','icon'=>'🕐','tier'=>'free','title'=>'timezone_name','subtitle'=>'utc_offset','search'=>['continent','timezone_name','utc_offset','dst_info'],'list'=>['continent','timezone_name','utc_offset','dst_info'],'detail'=>['continent','timezone_name','utc_offset','dst_info','has_dst','last_modified'],'fields'=>['continent','timezone_name','utc_offset','dst_info','has_dst']],
        'dataset_files'=>['label'=>'Dataset Files','table'=>'dataset_files','icon'=>'CSV','tier'=>'pro','title'=>'filename','subtitle'=>'category','search'=>['path','scope','category','filename','country_code'],'list'=>['filename','category','country_code','row_count','is_populated'],'detail'=>['path','scope','category','filename','country_code','row_count','is_populated','headers_json'],'fields'=>['path','scope','category','filename','country_code','row_count','is_populated','headers_json']],
        'source_records'=>['label'=>'Source Records','table'=>'source_records','icon'=>'SRC','tier'=>'pro','title'=>'title','subtitle'=>'entity_type','search'=>['entity_type','entity_id','url','title','raw_text'],'list'=>['entity_type','entity_id','title','retrieved_at'],'detail'=>['source_id','entity_type','entity_id','url','title','retrieved_at','raw_hash','raw_text','screenshot_path'],'fields'=>['source_id','entity_type','entity_id','url','title','retrieved_at','raw_hash','raw_text','screenshot_path']],
        'change_log'=>['label'=>'Change Log','table'=>'entity_change_log','icon'=>'LOG','tier'=>'pro','title'=>'field_name','subtitle'=>'entity_type','search'=>['entity_type','entity_id','field_name','old_value','new_value','change_source'],'list'=>['entity_type','entity_id','field_name','changed_at','change_source'],'detail'=>['entity_type','entity_id','field_name','old_value','new_value','changed_at','change_source','confidence_score'],'fields'=>['entity_type','entity_id','field_name','old_value','new_value','change_source','confidence_score']],
        'import_batches'=>['label'=>'Import Batches','table'=>'import_batches','icon'=>'IMP','tier'=>'ultimate','title'=>'batch_name','subtitle'=>'status','search'=>['batch_name','source_file','module_key','status','notes'],'list'=>['batch_name','module_key','status','rows_total','rows_imported','rows_failed','started_at'],'detail'=>['batch_name','source_file','module_key','status','rows_total','rows_imported','rows_failed','started_at','finished_at','notes'],'fields'=>['batch_name','source_file','module_key','status','rows_total','rows_imported','rows_failed','notes']],
        'staging_records'=>['label'=>'Staging Records','table'=>'staging_import_records','icon'=>'STG','tier'=>'ultimate','title'=>'module_key','subtitle'=>'status','search'=>['module_key','status','row_json','issue_summary'],'list'=>['import_batch_id','module_key','source_row_number','status','issue_summary'],'detail'=>['import_batch_id','module_key','source_row_number','status','row_json','issue_summary','created_at'],'fields'=>['import_batch_id','module_key','source_row_number','status','row_json','issue_summary']],
        'export_logs'=>['label'=>'Export Logs','table'=>'export_logs','icon'=>'EXP','tier'=>'ultimate','title'=>'module_key','subtitle'=>'rows_exported','search'=>['module_key','filters_json'],'list'=>['user_id','module_key','rows_exported','created_at'],'detail'=>['user_id','module_key','filters_json','rows_exported','created_at'],'fields'=>['user_id','module_key','filters_json','rows_exported']]
    ];
}

function module_config(string $key): ?array {
    $m = modules(); return $m[$key] ?? null;
}

function module_key_from_page(string $page): ?string {
    $map = ['airlines'=>'airlines','airports'=>'airports','aircraft'=>'aircraft','aircraft-types'=>'aircraft_types','aircraft_types'=>'aircraft_types','lessors'=>'lessors','routes'=>'routes','regulatory'=>'regulatory','infrastructure'=>'navaids','commercial'=>'commercial_fares','reference'=>'ref_booking_classes','gds'=>'gds','iata-iosa'=>'iata_membership','countries'=>'countries'];
    return $map[$page] ?? null;
}

function module_pk(string $key): string {
    static $map = [
        'countries' => 'iso_alpha_2',
        'country_air_transport_stats' => 'iso_alpha_2',
        'airports' => 'ident',
        'airlines' => 'icao_code',
        'aircraft_types' => 'icao_code',
    ];
    return $map[$key] ?? 'id';
}
